# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties - https://fabricmc.net/develop/
minecraft_version=25w32a
yarn_mappings=25w32a+build.1
loader_version=0.17.0
loom_version=1.11-SNAPSHOT

# Fabric API
fabric_version=0.131.2+1.21.9

# Mod Properties
mod_version=4.0.0+1.21.9_b03
maven_group=com.github.sun-in-vr
archives_base_name=virtual-additions

modid = virtual_additions
