package com.github.suninvr.virtualadditions.registry;

import com.github.suninvr.virtualadditions.VirtualAdditions;
import com.github.suninvr.virtualadditions.block.*;
import net.fabricmc.fabric.api.object.builder.v1.block.type.BlockSetTypeBuilder;
import net.fabricmc.fabric.api.object.builder.v1.block.type.WoodTypeBuilder;
import net.fabricmc.fabric.api.registry.FlattenableBlockRegistry;
import net.fabricmc.fabric.api.registry.LandPathNodeTypesRegistry;
import net.fabricmc.fabric.api.registry.OxidizableBlocksRegistry;
import net.fabricmc.fabric.api.registry.StrippableBlockRegistry;
import net.minecraft.core.particles.ColorParticleOption;
import net.minecraft.core.particles.ParticleTypes;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.util.ColorRGBA;
import net.minecraft.util.valueproviders.UniformInt;
import net.minecraft.world.item.DyeColor;
import net.minecraft.world.level.block.*;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.block.state.BlockBehaviour.Properties;
import net.minecraft.world.level.block.state.properties.BlockSetType;
import net.minecraft.world.level.block.state.properties.WoodType;
import net.minecraft.world.level.material.MapColor;
import net.minecraft.world.level.material.PushReaction;
import net.minecraft.world.level.pathfinder.PathType;

import static com.github.suninvr.virtualadditions.VirtualAdditions.idOf;
import static com.github.suninvr.virtualadditions.VirtualAdditions.setBlocksInitialized;
import static com.github.suninvr.virtualadditions.registry.RegistryHelper.BlockRegistryHelper.register;

public class VABlocks {

    public static final SoundType ROPE_SOUND_GROUP = new SoundType(1.0F, 1.0F, VASoundEvents.BLOCK_ROPE_BREAK, VASoundEvents.BLOCK_ROPE_STEP, VASoundEvents.BLOCK_ROPE_PLACE, VASoundEvents.BLOCK_ROPE_HIT, VASoundEvents.BLOCK_ROPE_FALL);

    public static final Block CLIMBING_ROPE;
    public static final Block CLIMBING_ROPE_ANCHOR;
    public static final Block EXPOSED_CLIMBING_ROPE_ANCHOR;
    public static final Block WEATHERED_CLIMBING_ROPE_ANCHOR;
    public static final Block OXIDIZED_CLIMBING_ROPE_ANCHOR;
    public static final Block WAXED_CLIMBING_ROPE_ANCHOR;
    public static final Block WAXED_EXPOSED_CLIMBING_ROPE_ANCHOR;
    public static final Block WAXED_WEATHERED_CLIMBING_ROPE_ANCHOR;
    public static final Block WAXED_OXIDIZED_CLIMBING_ROPE_ANCHOR;
    public static final Block RAW_STEEL_BLOCK;
    public static final Block STEEL_BLOCK;
    public static final Block EXPOSED_STEEL_BLOCK;
    public static final Block WEATHERED_STEEL_BLOCK;
    public static final Block OXIDIZED_STEEL_BLOCK;
    public static final Block WAXED_STEEL_BLOCK;
    public static final Block WAXED_EXPOSED_STEEL_BLOCK;
    public static final Block WAXED_WEATHERED_STEEL_BLOCK;
    public static final Block WAXED_OXIDIZED_STEEL_BLOCK;
    public static final Block CUT_STEEL;
    public static final Block CUT_STEEL_STAIRS;
    public static final Block CUT_STEEL_SLAB;
    public static final Block EXPOSED_CUT_STEEL;
    public static final Block EXPOSED_CUT_STEEL_STAIRS;
    public static final Block EXPOSED_CUT_STEEL_SLAB;
    public static final Block WEATHERED_CUT_STEEL;
    public static final Block WEATHERED_CUT_STEEL_STAIRS;
    public static final Block WEATHERED_CUT_STEEL_SLAB;
    public static final Block OXIDIZED_CUT_STEEL;
    public static final Block OXIDIZED_CUT_STEEL_STAIRS;
    public static final Block OXIDIZED_CUT_STEEL_SLAB;
    public static final Block WAXED_CUT_STEEL;
    public static final Block WAXED_CUT_STEEL_STAIRS;
    public static final Block WAXED_CUT_STEEL_SLAB;
    public static final Block WAXED_EXPOSED_CUT_STEEL;
    public static final Block WAXED_EXPOSED_CUT_STEEL_STAIRS;
    public static final Block WAXED_EXPOSED_CUT_STEEL_SLAB;
    public static final Block WAXED_WEATHERED_CUT_STEEL;
    public static final Block WAXED_WEATHERED_CUT_STEEL_STAIRS;
    public static final Block WAXED_WEATHERED_CUT_STEEL_SLAB;
    public static final Block WAXED_OXIDIZED_CUT_STEEL;
    public static final Block WAXED_OXIDIZED_CUT_STEEL_STAIRS;
    public static final Block WAXED_OXIDIZED_CUT_STEEL_SLAB;
    public static final Block STEEL_GRATE;
    public static final Block EXPOSED_STEEL_GRATE;
    public static final Block WEATHERED_STEEL_GRATE;
    public static final Block OXIDIZED_STEEL_GRATE;
    public static final Block WAXED_STEEL_GRATE;
    public static final Block WAXED_EXPOSED_STEEL_GRATE;
    public static final Block WAXED_WEATHERED_STEEL_GRATE;
    public static final Block WAXED_OXIDIZED_STEEL_GRATE;
    public static final Block CHISELED_STEEL;
    public static final Block EXPOSED_CHISELED_STEEL;
    public static final Block WEATHERED_CHISELED_STEEL;
    public static final Block OXIDIZED_CHISELED_STEEL;
    public static final Block WAXED_CHISELED_STEEL;
    public static final Block WAXED_EXPOSED_CHISELED_STEEL;
    public static final Block WAXED_WEATHERED_CHISELED_STEEL;
    public static final Block WAXED_OXIDIZED_CHISELED_STEEL;
    public static final Block STEEL_FENCE;
    public static final Block EXPOSED_STEEL_FENCE;
    public static final Block WEATHERED_STEEL_FENCE;
    public static final Block OXIDIZED_STEEL_FENCE;
    public static final Block WAXED_STEEL_FENCE;
    public static final Block WAXED_EXPOSED_STEEL_FENCE;
    public static final Block WAXED_WEATHERED_STEEL_FENCE;
    public static final Block WAXED_OXIDIZED_STEEL_FENCE;
    public static final Block STEEL_DOOR;
    public static final Block EXPOSED_STEEL_DOOR;
    public static final Block WEATHERED_STEEL_DOOR;
    public static final Block OXIDIZED_STEEL_DOOR;
    public static final Block WAXED_STEEL_DOOR;
    public static final Block WAXED_EXPOSED_STEEL_DOOR;
    public static final Block WAXED_WEATHERED_STEEL_DOOR;
    public static final Block WAXED_OXIDIZED_STEEL_DOOR;
    public static final Block STEEL_TRAPDOOR;
    public static final Block EXPOSED_STEEL_TRAPDOOR;
    public static final Block WEATHERED_STEEL_TRAPDOOR;
    public static final Block OXIDIZED_STEEL_TRAPDOOR;
    public static final Block WAXED_STEEL_TRAPDOOR;
    public static final Block WAXED_EXPOSED_STEEL_TRAPDOOR;
    public static final Block WAXED_WEATHERED_STEEL_TRAPDOOR;
    public static final Block WAXED_OXIDIZED_STEEL_TRAPDOOR;
    public static final Block REDSTONE_BRIDGE;
    public static final Block SPOTLIGHT;
    public static final Block SPOTLIGHT_LIGHT;
    public static final Block CAGELIGHT;
    public static final Block HORNFELS;
    public static final Block COBBLED_HORNFELS;
    public static final Block COBBLED_HORNFELS_STAIRS;
    public static final Block COBBLED_HORNFELS_SLAB;
    public static final Block COBBLED_HORNFELS_WALL;
    public static final Block POLISHED_HORNFELS;
    public static final Block POLISHED_HORNFELS_STAIRS;
    public static final Block POLISHED_HORNFELS_SLAB;
    public static final Block HORNFELS_TILES;
    public static final Block CRACKED_HORNFELS_TILES;
    public static final Block HORNFELS_TILE_STAIRS;
    public static final Block HORNFELS_TILE_SLAB;
    public static final Block CHISELED_HORNFELS;
    public static final Block CHISELED_HORNFELS_TILES;
    public static final Block BLUESCHIST;
    public static final Block COBBLED_BLUESCHIST;
    public static final Block COBBLED_BLUESCHIST_STAIRS;
    public static final Block COBBLED_BLUESCHIST_SLAB;
    public static final Block COBBLED_BLUESCHIST_WALL;
    public static final Block POLISHED_BLUESCHIST;
    public static final Block POLISHED_BLUESCHIST_STAIRS;
    public static final Block POLISHED_BLUESCHIST_SLAB;
    public static final Block POLISHED_BLUESCHIST_WALL;
    public static final Block BLUESCHIST_BRICKS;
    public static final Block CRACKED_BLUESCHIST_BRICKS;
    public static final Block BLUESCHIST_BRICK_STAIRS;
    public static final Block BLUESCHIST_BRICK_SLAB;
    public static final Block BLUESCHIST_BRICK_WALL;
    public static final Block CHISELED_BLUESCHIST;
    public static final Block SYENITE;
    public static final Block COBBLED_SYENITE;
    public static final Block COBBLED_SYENITE_STAIRS;
    public static final Block COBBLED_SYENITE_SLAB;
    public static final Block COBBLED_SYENITE_WALL;
    public static final Block POLISHED_SYENITE;
    public static final Block POLISHED_SYENITE_STAIRS;
    public static final Block POLISHED_SYENITE_SLAB;
    public static final Block POLISHED_SYENITE_WALL;
    public static final Block SYENITE_BRICKS;
    public static final Block CRACKED_SYENITE_BRICKS;
    public static final Block SYENITE_BRICK_STAIRS;
    public static final Block SYENITE_BRICK_SLAB;
    public static final Block SYENITE_BRICK_WALL;
    public static final Block CHISELED_SYENITE;
    public static final Block ROCK_SALT_BLOCK;
    public static final Block ROCK_SALT_BRICKS;
    public static final Block ROCK_SALT_BRICK_STAIRS;
    public static final Block ROCK_SALT_BRICK_SLAB;
    public static final Block ROCK_SALT_BRICK_WALL;
    public static final Block CHISELED_ROCK_SALT_BRICKS;
    public static final Block ROCK_SALT_CRYSTAL;
    public static final Block ROCK_SALT_ORE;
    public static final Block DEEPSLATE_ROCK_SALT_ORE;
    public static final Block COTTON;
    public static final Block CORN_CROP;
    public static final Block TOMATO;
    public static final Block CABBAGE;
    public static final Block WISDOM_BERRY;
    public static final Block PORPHYRY;
    public static final Block PORPHYRY_STAIRS;
    public static final Block PORPHYRY_SLAB;
    public static final Block PORPHYRY_WALL;
    public static final Block PORPHYRY_BRICKS;
    public static final Block PORPHYRY_BRICK_STAIRS;
    public static final Block PORPHYRY_BRICK_SLAB;
    public static final Block PORPHYRY_BRICK_WALL;
    public static final Block POLISHED_PORPHYRY;
    public static final Block POLISHED_PORPHYRY_STAIRS;
    public static final Block POLISHED_PORPHYRY_SLAB;
    public static final Block POLISHED_PORPHYRY_WALL;
    public static final Block SMALL_SPRING_LOTUS;
    public static final Block POTTED_SMALL_SPRING_LOTUS;
    public static final Block SPRING_LOTUS;
    public static final Block SOULBLOOM_LOG;
    public static final Block SOULBLOOM_WOOD;
    public static final Block STRIPPED_SOULBLOOM_LOG;
    public static final Block STRIPPED_SOULBLOOM_WOOD;
    public static final Block SOULBLOOM_PLANKS;
    public static final Block SOULBLOOM_STAIRS;
    public static final Block SOULBLOOM_SLAB;
    public static final Block SOULBLOOM_FENCE;
    public static final Block SOULBLOOM_FENCE_GATE;
    public static final Block SOULBLOOM_DOOR;
    public static final Block SOULBLOOM_TRAPDOOR;
    public static final Block SOULBLOOM_PRESSURE_PLATE;
    public static final Block SOULBLOOM_BUTTON;
    public static final Block SOULBLOOM_SIGN;
    public static final Block SOULBLOOM_WALL_SIGN;
    public static final Block SOULBLOOM_HANGING_SIGN;
    public static final Block SOULBLOOM_WALL_HANGING_SIGN;
    public static final Block SOULBLOOM_SHELF;
    public static final Block SOULBLOOM_LEAVES;
    public static final Block SOULBLOOM_SAPLING;
    public static final Block POTTED_SOULBLOOM_SAPLING;
    public static final Block BLUE_PETALS;
    public static final Block SOUL_SPROUT;
    public static final Block POTTED_SOUL_SPROUT;
    public static final Block BALLOON_BULB;
    public static final Block BALLOON_BULB_PLANT;
    public static final Block BALLOON_BULB_BUD;
    public static final Block NECROTIC_NYLIUM;
    public static final Block NECROTIC_ROOTS;
    public static final Block POTTED_NECROTIC_ROOTS;
    public static final Block BONE_LITTER;
    public static final Block BONE_PILE;
    public static final Block WITHERED_LOG;
    public static final Block WITHERED_WOOD;
    public static final Block STRIPPED_WITHERED_LOG;
    public static final Block STRIPPED_WITHERED_WOOD;
    public static final Block WITHERED_PLANKS;
    public static final Block WITHERED_STAIRS;
    public static final Block WITHERED_SLAB;
    public static final Block WITHERED_FENCE;
    public static final Block WITHERED_FENCE_GATE;
    public static final Block WITHERED_DOOR;
    public static final Block WITHERED_TRAPDOOR;
    public static final Block WITHERED_PRESSURE_PLATE;
    public static final Block WITHERED_BUTTON;
    public static final Block WITHERED_SIGN;
    public static final Block WITHERED_WALL_SIGN;
    public static final Block WITHERED_HANGING_SIGN;
    public static final Block WITHERED_WALL_HANGING_SIGN;
    public static final Block WITHERED_SHELF;
    public static final Block WITHERED_LEAVES;
    public static final Block WITHERED_SAPLING;
    public static final Block POTTED_WITHERED_SAPLING;
    public static final Block SPECTRAL_FIRE;
    public static final Block SPECTRAL_TORCH;
    public static final Block SPECTRAL_WALL_TORCH;
    public static final Block SPECTRAL_LANTERN;
    public static final Block SPECTRAL_SAND;
    public static final Block OAK_HEDGE;
    public static final Block SPRUCE_HEDGE;
    public static final Block BIRCH_HEDGE;
    public static final Block JUNGLE_HEDGE;
    public static final Block ACACIA_HEDGE;
    public static final Block DARK_OAK_HEDGE;
    public static final Block PALE_OAK_HEDGE;
    public static final Block MANGROVE_HEDGE;
    public static final Block CHERRY_HEDGE;
    public static final Block SOULBLOOM_HEDGE;
    public static final Block WITHERED_HEDGE;
    public static final Block AZALEA_HEDGE;
    public static final Block FLOWERING_AZALEA_HEDGE;
    public static final Block GLOWING_SILK;
    public static final Block FRAYED_SILK;
    public static final Block LUMWASP_NEST;
    public static final Block SILK_BLOCK;
    public static final Block GREENCAP_MUSHROOM;
    public static final Block TALL_GREENCAP_MUSHROOMS;
    public static final Block POTTED_GREENCAP_MUSHROOM;
    public static final Block WEBBED_SILK;
    public static final Block SILKBULB;
    public static final Block WHITE_SILKBULB;
    public static final Block LIGHT_GRAY_SILKBULB;
    public static final Block GRAY_SILKBULB;
    public static final Block BLACK_SILKBULB;
    public static final Block BROWN_SILKBULB;
    public static final Block RED_SILKBULB;
    public static final Block ORANGE_SILKBULB;
    public static final Block YELLOW_SILKBULB;
    public static final Block LIME_SILKBULB;
    public static final Block GREEN_SILKBULB;
    public static final Block CYAN_SILKBULB;
    public static final Block LIGHT_BLUE_SILKBULB;
    public static final Block BLUE_SILKBULB;
    public static final Block PURPLE_SILKBULB;
    public static final Block MAGENTA_SILKBULB;
    public static final Block PINK_SILKBULB;
    public static final Block CHARTREUSE_WOOL;
    public static final Block CHARTREUSE_CARPET;
    public static final Block CHARTREUSE_TERRACOTTA;
    public static final Block CHARTREUSE_CONCRETE;
    public static final Block CHARTREUSE_CONCRETE_POWDER;
    public static final Block CHARTREUSE_STAINED_GLASS;
    public static final Block CHARTREUSE_STAINED_GLASS_PANE;
    public static final Block CHARTREUSE_SILKBULB;
    public static final Block CHARTREUSE_CANDLE;
    public static final Block CHARTREUSE_CANDLE_CAKE;
    public static final Block CHARTREUSE_BED;
    public static final Block CHARTREUSE_SHULKER_BOX;
    public static final Block CHARTREUSE_BANNER;
    public static final Block CHARTREUSE_WALL_BANNER;
    public static final Block CHARTREUSE_GLAZED_TERRACOTTA;
    public static final Block MAROON_WOOL;
    public static final Block MAROON_CARPET;
    public static final Block MAROON_TERRACOTTA;
    public static final Block MAROON_CONCRETE;
    public static final Block MAROON_CONCRETE_POWDER;
    public static final Block MAROON_STAINED_GLASS;
    public static final Block MAROON_STAINED_GLASS_PANE;
    public static final Block MAROON_SILKBULB;
    public static final Block MAROON_CANDLE;
    public static final Block MAROON_CANDLE_CAKE;
    public static final Block MAROON_BED;
    public static final Block MAROON_SHULKER_BOX;
    public static final Block MAROON_BANNER;
    public static final Block MAROON_WALL_BANNER;
    public static final Block MAROON_GLAZED_TERRACOTTA;
    public static final Block INDIGO_WOOL;
    public static final Block INDIGO_CARPET;
    public static final Block INDIGO_TERRACOTTA;
    public static final Block INDIGO_CONCRETE;
    public static final Block INDIGO_CONCRETE_POWDER;
    public static final Block INDIGO_STAINED_GLASS;
    public static final Block INDIGO_STAINED_GLASS_PANE;
    public static final Block INDIGO_SILKBULB;
    public static final Block INDIGO_CANDLE;
    public static final Block INDIGO_CANDLE_CAKE;
    public static final Block INDIGO_BED;
    public static final Block INDIGO_SHULKER_BOX;
    public static final Block INDIGO_BANNER;
    public static final Block INDIGO_WALL_BANNER;
    public static final Block INDIGO_GLAZED_TERRACOTTA;
    public static final Block PLUM_WOOL;
    public static final Block PLUM_CARPET;
    public static final Block PLUM_TERRACOTTA;
    public static final Block PLUM_CONCRETE;
    public static final Block PLUM_CONCRETE_POWDER;
    public static final Block PLUM_STAINED_GLASS;
    public static final Block PLUM_STAINED_GLASS_PANE;
    public static final Block PLUM_SILKBULB;
    public static final Block PLUM_CANDLE;
    public static final Block PLUM_CANDLE_CAKE;
    public static final Block PLUM_BED;
    public static final Block PLUM_SHULKER_BOX;
    public static final Block PLUM_BANNER;
    public static final Block PLUM_WALL_BANNER;
    public static final Block PLUM_GLAZED_TERRACOTTA;
    public static final Block VIRIDIAN_WOOL;
    public static final Block VIRIDIAN_CARPET;
    public static final Block VIRIDIAN_TERRACOTTA;
    public static final Block VIRIDIAN_CONCRETE;
    public static final Block VIRIDIAN_CONCRETE_POWDER;
    public static final Block VIRIDIAN_STAINED_GLASS;
    public static final Block VIRIDIAN_STAINED_GLASS_PANE;
    public static final Block VIRIDIAN_SILKBULB;
    public static final Block VIRIDIAN_CANDLE;
    public static final Block VIRIDIAN_CANDLE_CAKE;
    public static final Block VIRIDIAN_BED;
    public static final Block VIRIDIAN_SHULKER_BOX;
    public static final Block VIRIDIAN_BANNER;
    public static final Block VIRIDIAN_WALL_BANNER;
    public static final Block VIRIDIAN_GLAZED_TERRACOTTA;
    public static final Block TAN_WOOL;
    public static final Block TAN_CARPET;
    public static final Block TAN_TERRACOTTA;
    public static final Block TAN_CONCRETE;
    public static final Block TAN_CONCRETE_POWDER;
    public static final Block TAN_STAINED_GLASS;
    public static final Block TAN_STAINED_GLASS_PANE;
    public static final Block TAN_SILKBULB;
    public static final Block TAN_CANDLE;
    public static final Block TAN_CANDLE_CAKE;
    public static final Block TAN_BED;
    public static final Block TAN_SHULKER_BOX;
    public static final Block TAN_BANNER;
    public static final Block TAN_WALL_BANNER;
    public static final Block TAN_GLAZED_TERRACOTTA;
    public static final Block SINOPIA_WOOL;
    public static final Block SINOPIA_CARPET;
    public static final Block SINOPIA_TERRACOTTA;
    public static final Block SINOPIA_CONCRETE;
    public static final Block SINOPIA_CONCRETE_POWDER;
    public static final Block SINOPIA_STAINED_GLASS;
    public static final Block SINOPIA_STAINED_GLASS_PANE;
    public static final Block SINOPIA_SILKBULB;
    public static final Block SINOPIA_CANDLE;
    public static final Block SINOPIA_CANDLE_CAKE;
    public static final Block SINOPIA_BED;
    public static final Block SINOPIA_SHULKER_BOX;
    public static final Block SINOPIA_BANNER;
    public static final Block SINOPIA_WALL_BANNER;
    public static final Block SINOPIA_GLAZED_TERRACOTTA;
    public static final Block LILAC_WOOL;
    public static final Block LILAC_CARPET;
    public static final Block LILAC_TERRACOTTA;
    public static final Block LILAC_CONCRETE;
    public static final Block LILAC_CONCRETE_POWDER;
    public static final Block LILAC_STAINED_GLASS;
    public static final Block LILAC_STAINED_GLASS_PANE;
    public static final Block LILAC_SILKBULB;
    public static final Block LILAC_CANDLE;
    public static final Block LILAC_CANDLE_CAKE;
    public static final Block LILAC_BED;
    public static final Block LILAC_SHULKER_BOX;
    public static final Block LILAC_BANNER;
    public static final Block LILAC_WALL_BANNER;
    public static final Block LILAC_GLAZED_TERRACOTTA;
    public static final Block COLORING_STATION;
    public static final Block ACID;
    public static final Block ACID_BLOCK;
    public static final Block IOLITE_ORE;
    public static final Block IOLITE_BLOCK;
    public static final Block MINI_PORTAL;
    public static final Block ENTANGLEMENT_DRIVE;
    public static final Block REMOTE_NOTIFIER;
    public static final Block DESTRUCTIVE_SCULK;

    public static final BlockSetType SOULBLOOM = BlockSetTypeBuilder.copyOf(BlockSetType.CHERRY).build(idOf("soulbloom"));
    public static final WoodType SOULBLOOM_WOODTYPE = WoodType.register(WoodTypeBuilder.copyOf(WoodType.CHERRY).build(idOf("soulbloom"), SOULBLOOM));
    public static final BlockSetType WITHERED = BlockSetTypeBuilder.copyOf(BlockSetType.WARPED).build(idOf("withered"));
    public static final WoodType WITHERED_WOODTYPE = WoodType.register(WoodTypeBuilder.copyOf(WoodType.WARPED).build(idOf("withered"), WITHERED));

    public static final BlockSetType STEEL_BLOCK_SET_TYPE;

    static {
        STEEL_BLOCK_SET_TYPE = new BlockSetType("steel", false, false, false, BlockSetType.PressurePlateSensitivity.EVERYTHING, SoundType.NETHERITE_BLOCK, SoundEvents.IRON_DOOR_CLOSE, SoundEvents.IRON_DOOR_OPEN, SoundEvents.IRON_TRAPDOOR_CLOSE, SoundEvents.IRON_TRAPDOOR_OPEN, SoundEvents.METAL_PRESSURE_PLATE_CLICK_OFF, SoundEvents.METAL_PRESSURE_PLATE_CLICK_ON, SoundEvents.STONE_BUTTON_CLICK_OFF, SoundEvents.STONE_BUTTON_CLICK_ON);

        CLIMBING_ROPE = register("climbing_rope", ClimbingRopeBlock::new, Properties.of().sound(ROPE_SOUND_GROUP).pushReaction(PushReaction.DESTROY).noCollision().noOcclusion().ignitedByLava().destroyTime(0.5F));
        CLIMBING_ROPE_ANCHOR = register("climbing_rope_anchor",  (settings) -> new OxidizableClimbingRopeAnchor(settings, WeatheringCopper.WeatherState.UNAFFECTED), (Properties.of().sound(ROPE_SOUND_GROUP).pushReaction(PushReaction.DESTROY).noCollision().noOcclusion().ignitedByLava().destroyTime(0.5F)));
        EXPOSED_CLIMBING_ROPE_ANCHOR = register("exposed_climbing_rope_anchor",  (settings) -> new OxidizableClimbingRopeAnchor(settings, WeatheringCopper.WeatherState.EXPOSED), (Properties.of().sound(ROPE_SOUND_GROUP).pushReaction(PushReaction.DESTROY).noCollision().noOcclusion().ignitedByLava().destroyTime(0.5F)));
        WEATHERED_CLIMBING_ROPE_ANCHOR = register("weathered_climbing_rope_anchor",  (settings) -> new OxidizableClimbingRopeAnchor(settings, WeatheringCopper.WeatherState.WEATHERED), (Properties.of().sound(ROPE_SOUND_GROUP).pushReaction(PushReaction.DESTROY).noCollision().noOcclusion().ignitedByLava().destroyTime(0.5F)));
        OXIDIZED_CLIMBING_ROPE_ANCHOR = register("oxidized_climbing_rope_anchor",  (settings) -> new OxidizableClimbingRopeAnchor(settings, WeatheringCopper.WeatherState.OXIDIZED), (Properties.of().sound(ROPE_SOUND_GROUP).pushReaction(PushReaction.DESTROY).noCollision().noOcclusion().ignitedByLava().destroyTime(0.5F)));
        WAXED_CLIMBING_ROPE_ANCHOR = register("waxed_climbing_rope_anchor", ClimbingRopeAnchorBlock::new, Properties.of().sound(ROPE_SOUND_GROUP).pushReaction(PushReaction.DESTROY).noCollision().noOcclusion().ignitedByLava().destroyTime(0.5F));
        WAXED_EXPOSED_CLIMBING_ROPE_ANCHOR = register("waxed_exposed_climbing_rope_anchor", ClimbingRopeAnchorBlock::new, Properties.of().sound(ROPE_SOUND_GROUP).pushReaction(PushReaction.DESTROY).noCollision().noOcclusion().ignitedByLava().destroyTime(0.5F));
        WAXED_WEATHERED_CLIMBING_ROPE_ANCHOR = register("waxed_weathered_climbing_rope_anchor", ClimbingRopeAnchorBlock::new, Properties.of().sound(ROPE_SOUND_GROUP).pushReaction(PushReaction.DESTROY).noCollision().noOcclusion().ignitedByLava().destroyTime(0.5F));
        WAXED_OXIDIZED_CLIMBING_ROPE_ANCHOR = register("waxed_oxidized_climbing_rope_anchor", ClimbingRopeAnchorBlock::new, Properties.of().sound(ROPE_SOUND_GROUP).pushReaction(PushReaction.DESTROY).noCollision().noOcclusion().ignitedByLava().destroyTime(0.5F));

        RAW_STEEL_BLOCK = register("raw_steel_block", Block::new, Properties.of().mapColor(MapColor.COLOR_GRAY).requiresCorrectToolForDrops().strength(5.0F, 300.0F));
        STEEL_BLOCK = register("steel_block", (settings) -> new WeatheringCopperFullBlock(WeatheringCopper.WeatherState.UNAFFECTED, settings), Properties.of().mapColor(MapColor.COLOR_GRAY).sound(SoundType.NETHERITE_BLOCK).requiresCorrectToolForDrops().destroyTime(5.0F).explosionResistance(300.0F));
        CUT_STEEL = register("cut_steel", (settings) -> new WeatheringCopperFullBlock(WeatheringCopper.WeatherState.UNAFFECTED, settings), Properties.ofFullCopy(STEEL_BLOCK).strength(3.0F, 300.0F));
        CUT_STEEL_STAIRS = register("cut_steel_stairs", (settings) -> new WeatheringCopperStairBlock(WeatheringCopper.WeatherState.UNAFFECTED, CUT_STEEL.defaultBlockState(), settings), Properties.ofFullCopy(CUT_STEEL));
        CUT_STEEL_SLAB = register("cut_steel_slab", (settings) -> new WeatheringCopperSlabBlock(WeatheringCopper.WeatherState.UNAFFECTED, settings), Properties.ofFullCopy(CUT_STEEL));
        STEEL_GRATE = register("steel_grate", (settings) -> new WeatheringCopperGrateBlock(WeatheringCopper.WeatherState.UNAFFECTED, settings), Properties.ofFullCopy(CUT_STEEL).strength(2.0F, 300.0F).noOcclusion());
        CHISELED_STEEL = register("chiseled_steel", (settings) -> new WeatheringCopperFullBlock(WeatheringCopper.WeatherState.UNAFFECTED, settings), Properties.ofFullCopy(CUT_STEEL));
        STEEL_FENCE = register("steel_fence", (settings) -> new OxidizableFenceBlock( WeatheringCopper.WeatherState.UNAFFECTED, settings), Properties.ofFullCopy(CUT_STEEL));
        STEEL_DOOR = register("steel_door", (settings) -> new OxidizableSteelDoorBlock(WeatheringCopper.WeatherState.UNAFFECTED, settings), Properties.ofFullCopy(STEEL_BLOCK).noOcclusion().pushReaction(PushReaction.DESTROY));
        STEEL_TRAPDOOR = register("steel_trapdoor", (settings) -> new OxidizableSteelTrapdoorBlock(WeatheringCopper.WeatherState.UNAFFECTED, settings), Properties.ofFullCopy(STEEL_DOOR));

        EXPOSED_STEEL_BLOCK = register("exposed_steel_block", (settings) -> new WeatheringCopperFullBlock(WeatheringCopper.WeatherState.EXPOSED, settings), Properties.of().mapColor(MapColor.COLOR_GRAY).sound(SoundType.NETHERITE_BLOCK).requiresCorrectToolForDrops().destroyTime(5.0F).explosionResistance(300.0F));
        EXPOSED_CUT_STEEL = register("exposed_cut_steel", (settings) -> new WeatheringCopperFullBlock(WeatheringCopper.WeatherState.EXPOSED, settings), Properties.ofFullCopy(STEEL_BLOCK).strength(3.0F, 300.0F));
        EXPOSED_CUT_STEEL_STAIRS = register("exposed_cut_steel_stairs", (settings) -> new WeatheringCopperStairBlock(WeatheringCopper.WeatherState.EXPOSED, CUT_STEEL.defaultBlockState(), settings), Properties.ofFullCopy(CUT_STEEL));
        EXPOSED_CUT_STEEL_SLAB = register("exposed_cut_steel_slab", (settings) -> new WeatheringCopperSlabBlock(WeatheringCopper.WeatherState.EXPOSED, settings), Properties.ofFullCopy(CUT_STEEL));
        EXPOSED_STEEL_GRATE = register("exposed_steel_grate", (settings) -> new WeatheringCopperGrateBlock(WeatheringCopper.WeatherState.EXPOSED, settings), Properties.ofFullCopy(CUT_STEEL).strength(2.0F, 300.0F).noOcclusion());
        EXPOSED_CHISELED_STEEL = register("exposed_chiseled_steel", (settings) -> new WeatheringCopperFullBlock(WeatheringCopper.WeatherState.EXPOSED, settings), Properties.ofFullCopy(CUT_STEEL));
        EXPOSED_STEEL_FENCE = register("exposed_steel_fence", (settings) -> new OxidizableFenceBlock( WeatheringCopper.WeatherState.EXPOSED, settings), Properties.ofFullCopy(CUT_STEEL));
        EXPOSED_STEEL_DOOR = register("exposed_steel_door", (settings) -> new OxidizableSteelDoorBlock(WeatheringCopper.WeatherState.EXPOSED, settings), Properties.ofFullCopy(STEEL_BLOCK).noOcclusion().pushReaction(PushReaction.DESTROY));
        EXPOSED_STEEL_TRAPDOOR = register("exposed_steel_trapdoor", (settings) -> new OxidizableSteelTrapdoorBlock(WeatheringCopper.WeatherState.EXPOSED, settings), Properties.ofFullCopy(STEEL_DOOR));

        WEATHERED_STEEL_BLOCK = register("weathered_steel_block", (settings) -> new WeatheringCopperFullBlock(WeatheringCopper.WeatherState.WEATHERED, settings), Properties.of().mapColor(MapColor.COLOR_GRAY).sound(SoundType.NETHERITE_BLOCK).requiresCorrectToolForDrops().destroyTime(5.0F).explosionResistance(300.0F));
        WEATHERED_CUT_STEEL = register("weathered_cut_steel", (settings) -> new WeatheringCopperFullBlock(WeatheringCopper.WeatherState.WEATHERED, settings), Properties.ofFullCopy(STEEL_BLOCK).strength(3.0F, 300.0F));
        WEATHERED_CUT_STEEL_STAIRS = register("weathered_cut_steel_stairs", (settings) -> new WeatheringCopperStairBlock(WeatheringCopper.WeatherState.WEATHERED, CUT_STEEL.defaultBlockState(), settings), Properties.ofFullCopy(CUT_STEEL));
        WEATHERED_CUT_STEEL_SLAB = register("weathered_cut_steel_slab", (settings) -> new WeatheringCopperSlabBlock(WeatheringCopper.WeatherState.WEATHERED, settings), Properties.ofFullCopy(CUT_STEEL));
        WEATHERED_STEEL_GRATE = register("weathered_steel_grate", (settings) -> new WeatheringCopperGrateBlock(WeatheringCopper.WeatherState.WEATHERED, settings), Properties.ofFullCopy(CUT_STEEL).strength(2.0F, 300.0F).noOcclusion());
        WEATHERED_CHISELED_STEEL = register("weathered_chiseled_steel", (settings) -> new WeatheringCopperFullBlock(WeatheringCopper.WeatherState.WEATHERED, settings), Properties.ofFullCopy(CUT_STEEL));
        WEATHERED_STEEL_FENCE = register("weathered_steel_fence", (settings) -> new OxidizableFenceBlock( WeatheringCopper.WeatherState.WEATHERED, settings), Properties.ofFullCopy(CUT_STEEL));
        WEATHERED_STEEL_DOOR = register("weathered_steel_door", (settings) -> new OxidizableSteelDoorBlock(WeatheringCopper.WeatherState.WEATHERED, settings), Properties.ofFullCopy(STEEL_BLOCK).noOcclusion().pushReaction(PushReaction.DESTROY));
        WEATHERED_STEEL_TRAPDOOR = register("weathered_steel_trapdoor", (settings) -> new OxidizableSteelTrapdoorBlock(WeatheringCopper.WeatherState.WEATHERED, settings), Properties.ofFullCopy(STEEL_DOOR));

        OXIDIZED_STEEL_BLOCK = register("oxidized_steel_block", (settings) -> new WeatheringCopperFullBlock(WeatheringCopper.WeatherState.OXIDIZED, settings), Properties.of().mapColor(MapColor.COLOR_GRAY).sound(SoundType.NETHERITE_BLOCK).requiresCorrectToolForDrops().destroyTime(5.0F).explosionResistance(300.0F));
        OXIDIZED_CUT_STEEL = register("oxidized_cut_steel", (settings) -> new WeatheringCopperFullBlock(WeatheringCopper.WeatherState.OXIDIZED, settings), Properties.ofFullCopy(STEEL_BLOCK).strength(3.0F, 300.0F));
        OXIDIZED_CUT_STEEL_STAIRS = register("oxidized_cut_steel_stairs", (settings) -> new WeatheringCopperStairBlock(WeatheringCopper.WeatherState.OXIDIZED, CUT_STEEL.defaultBlockState(), settings), Properties.ofFullCopy(CUT_STEEL));
        OXIDIZED_CUT_STEEL_SLAB = register("oxidized_cut_steel_slab", (settings) -> new WeatheringCopperSlabBlock(WeatheringCopper.WeatherState.OXIDIZED, settings), Properties.ofFullCopy(CUT_STEEL));
        OXIDIZED_STEEL_GRATE = register("oxidized_steel_grate", (settings) -> new WeatheringCopperGrateBlock(WeatheringCopper.WeatherState.OXIDIZED, settings), Properties.ofFullCopy(CUT_STEEL).strength(2.0F, 300.0F).noOcclusion());
        OXIDIZED_CHISELED_STEEL = register("oxidized_chiseled_steel", (settings) -> new WeatheringCopperFullBlock(WeatheringCopper.WeatherState.OXIDIZED, settings), Properties.ofFullCopy(CUT_STEEL));
        OXIDIZED_STEEL_FENCE = register("oxidized_steel_fence", (settings) -> new OxidizableFenceBlock( WeatheringCopper.WeatherState.OXIDIZED, settings), Properties.ofFullCopy(CUT_STEEL));
        OXIDIZED_STEEL_DOOR = register("oxidized_steel_door", (settings) -> new OxidizableSteelDoorBlock(WeatheringCopper.WeatherState.OXIDIZED, settings), Properties.ofFullCopy(STEEL_BLOCK).noOcclusion().pushReaction(PushReaction.DESTROY));
        OXIDIZED_STEEL_TRAPDOOR = register("oxidized_steel_trapdoor", (settings) -> new OxidizableSteelTrapdoorBlock(WeatheringCopper.WeatherState.OXIDIZED, settings), Properties.ofFullCopy(STEEL_DOOR));

        WAXED_STEEL_BLOCK = register("waxed_steel_block", Block::new, (Properties.of().mapColor(MapColor.COLOR_GRAY).sound(SoundType.NETHERITE_BLOCK).requiresCorrectToolForDrops().destroyTime(5.0F).explosionResistance(300.0F)));
        WAXED_CUT_STEEL = register("waxed_cut_steel", Block::new, (Properties.ofFullCopy(STEEL_BLOCK).strength(3.0F, 300.0F)));
        WAXED_CUT_STEEL_STAIRS = register("waxed_cut_steel_stairs", settings -> new StairBlock(CUT_STEEL.defaultBlockState(), settings), Properties.ofFullCopy(CUT_STEEL));
        WAXED_CUT_STEEL_SLAB = register("waxed_cut_steel_slab", SlabBlock::new, (Properties.ofFullCopy(CUT_STEEL)));
        WAXED_STEEL_GRATE = register("waxed_steel_grate", WaterloggedTransparentBlock::new, (Properties.ofFullCopy(CUT_STEEL).strength(2.0F, 300.0F).noOcclusion()));
        WAXED_CHISELED_STEEL = register("waxed_chiseled_steel", Block::new, (Properties.ofFullCopy(CUT_STEEL)));
        WAXED_STEEL_FENCE = register("waxed_steel_fence", FenceBlock::new, Properties.ofFullCopy(CUT_STEEL));
        WAXED_STEEL_DOOR = register("waxed_steel_door", SteelDoorBlock::new, (Properties.ofFullCopy(STEEL_BLOCK).noOcclusion().pushReaction(PushReaction.DESTROY)));
        WAXED_STEEL_TRAPDOOR = register("waxed_steel_trapdoor", SteelTrapdoorBlock::new, (Properties.ofFullCopy(STEEL_DOOR)));

        WAXED_EXPOSED_STEEL_BLOCK = register("waxed_exposed_steel_block", Block::new, (Properties.of().mapColor(MapColor.COLOR_GRAY).sound(SoundType.NETHERITE_BLOCK).requiresCorrectToolForDrops().destroyTime(5.0F).explosionResistance(300.0F)));
        WAXED_EXPOSED_CUT_STEEL = register("waxed_exposed_cut_steel", Block::new, (Properties.ofFullCopy(STEEL_BLOCK).strength(3.0F, 300.0F)));
        WAXED_EXPOSED_CUT_STEEL_STAIRS = register("waxed_exposed_cut_steel_stairs", settings -> new StairBlock(EXPOSED_CUT_STEEL.defaultBlockState(), settings), Properties.ofFullCopy(EXPOSED_CUT_STEEL));
        WAXED_EXPOSED_CUT_STEEL_SLAB = register("waxed_exposed_cut_steel_slab", SlabBlock::new, (Properties.ofFullCopy(EXPOSED_CUT_STEEL)));
        WAXED_EXPOSED_STEEL_GRATE = register("waxed_exposed_steel_grate", WaterloggedTransparentBlock::new, (Properties.ofFullCopy(CUT_STEEL).strength(2.0F, 300.0F).noOcclusion()));
        WAXED_EXPOSED_CHISELED_STEEL = register("waxed_exposed_chiseled_steel", Block::new, (Properties.ofFullCopy(CUT_STEEL)));
        WAXED_EXPOSED_STEEL_FENCE = register("waxed_exposed_steel_fence", FenceBlock::new, Properties.ofFullCopy(CUT_STEEL));
        WAXED_EXPOSED_STEEL_DOOR = register("waxed_exposed_steel_door", SteelDoorBlock::new, (Properties.ofFullCopy(STEEL_BLOCK).noOcclusion().pushReaction(PushReaction.DESTROY)));
        WAXED_EXPOSED_STEEL_TRAPDOOR = register("waxed_exposed_steel_trapdoor", SteelTrapdoorBlock::new, (Properties.ofFullCopy(STEEL_DOOR)));

        WAXED_WEATHERED_STEEL_BLOCK = register("waxed_weathered_steel_block", Block::new, (Properties.of().mapColor(MapColor.COLOR_GRAY).sound(SoundType.NETHERITE_BLOCK).requiresCorrectToolForDrops().destroyTime(5.0F).explosionResistance(300.0F)));
        WAXED_WEATHERED_CUT_STEEL = register("waxed_weathered_cut_steel", Block::new, (Properties.ofFullCopy(STEEL_BLOCK).strength(3.0F, 300.0F)));
        WAXED_WEATHERED_CUT_STEEL_STAIRS = register("waxed_weathered_cut_steel_stairs", settings -> new StairBlock(WEATHERED_CUT_STEEL.defaultBlockState(), settings), Properties.ofFullCopy(WEATHERED_CUT_STEEL));
        WAXED_WEATHERED_CUT_STEEL_SLAB = register("waxed_weathered_cut_steel_slab", SlabBlock::new, (Properties.ofFullCopy(WEATHERED_CUT_STEEL)));
        WAXED_WEATHERED_STEEL_GRATE = register("waxed_weathered_steel_grate", WaterloggedTransparentBlock::new, (Properties.ofFullCopy(CUT_STEEL).strength(2.0F, 300.0F).noOcclusion()));
        WAXED_WEATHERED_CHISELED_STEEL = register("waxed_weathered_chiseled_steel", Block::new, (Properties.ofFullCopy(CUT_STEEL)));
        WAXED_WEATHERED_STEEL_FENCE = register("waxed_weathered_steel_fence", FenceBlock::new, Properties.ofFullCopy(CUT_STEEL));
        WAXED_WEATHERED_STEEL_DOOR = register("waxed_weathered_steel_door", SteelDoorBlock::new, (Properties.ofFullCopy(STEEL_BLOCK).noOcclusion().pushReaction(PushReaction.DESTROY)));
        WAXED_WEATHERED_STEEL_TRAPDOOR = register("waxed_weathered_steel_trapdoor", SteelTrapdoorBlock::new, (Properties.ofFullCopy(STEEL_DOOR)));

        WAXED_OXIDIZED_STEEL_BLOCK = register("waxed_oxidized_steel_block", Block::new, (Properties.of().mapColor(MapColor.COLOR_GRAY).sound(SoundType.NETHERITE_BLOCK).requiresCorrectToolForDrops().destroyTime(5.0F).explosionResistance(300.0F)));
        WAXED_OXIDIZED_CUT_STEEL = register("waxed_oxidized_cut_steel", Block::new, (Properties.ofFullCopy(STEEL_BLOCK).strength(3.0F, 300.0F)));
        WAXED_OXIDIZED_CUT_STEEL_STAIRS = register("waxed_oxidized_cut_steel_stairs", settings -> new StairBlock(OXIDIZED_CUT_STEEL.defaultBlockState(), settings), Properties.ofFullCopy(OXIDIZED_CUT_STEEL));
        WAXED_OXIDIZED_CUT_STEEL_SLAB = register("waxed_oxidized_cut_steel_slab", SlabBlock::new, (Properties.ofFullCopy(OXIDIZED_CUT_STEEL)));
        WAXED_OXIDIZED_STEEL_GRATE = register("waxed_oxidized_steel_grate", WaterloggedTransparentBlock::new, (Properties.ofFullCopy(CUT_STEEL).strength(2.0F, 300.0F).noOcclusion()));
        WAXED_OXIDIZED_CHISELED_STEEL = register("waxed_oxidized_chiseled_steel", Block::new, (Properties.ofFullCopy(CUT_STEEL)));
        WAXED_OXIDIZED_STEEL_FENCE = register("waxed_oxidized_steel_fence", FenceBlock::new, Properties.ofFullCopy(CUT_STEEL));
        WAXED_OXIDIZED_STEEL_DOOR = register("waxed_oxidized_steel_door", SteelDoorBlock::new, (Properties.ofFullCopy(STEEL_BLOCK).noOcclusion().pushReaction(PushReaction.DESTROY)));
        WAXED_OXIDIZED_STEEL_TRAPDOOR = register("waxed_oxidized_steel_trapdoor", SteelTrapdoorBlock::new, (Properties.ofFullCopy(STEEL_DOOR)));


        REDSTONE_BRIDGE = register("redstone_bridge", RedstoneBridgeBlock::new, Properties.ofFullCopy(STEEL_GRATE));
        CAGELIGHT = register("cagelight", ThinPillarBlock::new, Properties.ofFullCopy(STEEL_GRATE).noOcclusion().emissiveRendering((state, world, pos) -> true).lightLevel( (state) -> 11 ) );

        HORNFELS = register("hornfels", RotatedPillarBlock::new, Properties.ofFullCopy(Blocks.DEEPSLATE));
        COBBLED_HORNFELS = register("cobbled_hornfels", Block::new  , Properties.ofFullCopy(Blocks.COBBLED_DEEPSLATE));
        COBBLED_HORNFELS_STAIRS = register("cobbled_hornfels_stairs", (settings) -> new CustomStairsBlock(COBBLED_HORNFELS.defaultBlockState(), settings), Properties.ofFullCopy(Blocks.COBBLED_DEEPSLATE));
        COBBLED_HORNFELS_SLAB = register("cobbled_hornfels_slab", SlabBlock::new, Properties.ofFullCopy(Blocks.COBBLED_DEEPSLATE));
        COBBLED_HORNFELS_WALL = register("cobbled_hornfels_wall", WallBlock::new, Properties.ofFullCopy(Blocks.COBBLED_DEEPSLATE));
        POLISHED_HORNFELS = register("polished_hornfels", RotatedPillarBlock::new, Properties.ofFullCopy(Blocks.POLISHED_DEEPSLATE));
        POLISHED_HORNFELS_STAIRS = register("polished_hornfels_stairs", (settings) -> new CustomStairsBlock(POLISHED_HORNFELS.defaultBlockState(), settings), Properties.ofFullCopy(Blocks.POLISHED_DEEPSLATE_STAIRS));
        POLISHED_HORNFELS_SLAB = register("polished_hornfels_slab", SlabBlock::new, Properties.ofFullCopy(Blocks.POLISHED_DEEPSLATE_SLAB));
        HORNFELS_TILES = register("hornfels_tiles", Block::new, Properties.ofFullCopy(Blocks.DEEPSLATE_TILES));
        CRACKED_HORNFELS_TILES = register("cracked_hornfels_tiles", Block::new, Properties.ofFullCopy(Blocks.DEEPSLATE_TILES));
        HORNFELS_TILE_STAIRS = register("hornfels_tile_stairs", (settings) -> new CustomStairsBlock(HORNFELS_TILES.defaultBlockState(), settings), Properties.ofFullCopy(Blocks.DEEPSLATE_TILE_STAIRS));
        HORNFELS_TILE_SLAB = register("hornfels_tile_slab", SlabBlock::new, Properties.ofFullCopy(Blocks.DEEPSLATE_TILE_SLAB));
        CHISELED_HORNFELS = register("chiseled_hornfels", Block::new, Properties.ofFullCopy(VABlocks.POLISHED_HORNFELS));
        CHISELED_HORNFELS_TILES = register("chiseled_hornfels_tiles", Block::new, Properties.ofFullCopy(VABlocks.HORNFELS_TILES));

        BLUESCHIST = register("blueschist", Block::new, Properties.ofFullCopy(Blocks.DEEPSLATE));
        COBBLED_BLUESCHIST = register("cobbled_blueschist", Block::new, Properties.ofFullCopy(Blocks.COBBLED_DEEPSLATE));
        COBBLED_BLUESCHIST_STAIRS = register("cobbled_blueschist_stairs", (settings) -> new CustomStairsBlock(VABlocks.COBBLED_BLUESCHIST.defaultBlockState(), settings), Properties.ofFullCopy(Blocks.COBBLED_DEEPSLATE));
        COBBLED_BLUESCHIST_SLAB = register("cobbled_blueschist_slab", SlabBlock::new, Properties.ofFullCopy(Blocks.COBBLED_DEEPSLATE));
        COBBLED_BLUESCHIST_WALL = register("cobbled_blueschist_wall", WallBlock::new, Properties.ofFullCopy(Blocks.COBBLED_DEEPSLATE));
        POLISHED_BLUESCHIST = register("polished_blueschist", Block::new, Properties.ofFullCopy(Blocks.POLISHED_DEEPSLATE));
        POLISHED_BLUESCHIST_STAIRS = register("polished_blueschist_stairs", (settings) -> new CustomStairsBlock(POLISHED_BLUESCHIST.defaultBlockState(), settings), Properties.ofFullCopy(Blocks.POLISHED_DEEPSLATE_STAIRS));
        POLISHED_BLUESCHIST_SLAB = register("polished_blueschist_slab", SlabBlock::new, Properties.ofFullCopy(Blocks.POLISHED_DEEPSLATE_SLAB));
        POLISHED_BLUESCHIST_WALL = register("polished_blueschist_wall", WallBlock::new, Properties.ofFullCopy(Blocks.POLISHED_DEEPSLATE_WALL));
        BLUESCHIST_BRICKS = register("blueschist_bricks", Block::new, Properties.ofFullCopy(Blocks.DEEPSLATE_BRICKS));
        CRACKED_BLUESCHIST_BRICKS = register("cracked_blueschist_bricks", Block::new, Properties.ofFullCopy(Blocks.DEEPSLATE_BRICKS));
        BLUESCHIST_BRICK_STAIRS = register("blueschist_brick_stairs", (settings) -> new CustomStairsBlock(BLUESCHIST_BRICKS.defaultBlockState(), settings), Properties.ofFullCopy(Blocks.DEEPSLATE_BRICK_STAIRS));
        BLUESCHIST_BRICK_SLAB = register("blueschist_brick_slab", SlabBlock::new, Properties.ofFullCopy(Blocks.DEEPSLATE_BRICK_SLAB));
        BLUESCHIST_BRICK_WALL = register("blueschist_brick_wall", WallBlock::new, Properties.ofFullCopy(Blocks.DEEPSLATE_BRICK_WALL));
        CHISELED_BLUESCHIST = register("chiseled_blueschist", Block::new, Properties.ofFullCopy(VABlocks.BLUESCHIST_BRICKS));

        SYENITE = register("syenite", Block::new, Properties.ofFullCopy(Blocks.DEEPSLATE));
        COBBLED_SYENITE = register("cobbled_syenite", Block::new, Properties.ofFullCopy(Blocks.COBBLED_DEEPSLATE));
        COBBLED_SYENITE_STAIRS = register("cobbled_syenite_stairs", (settings) -> new CustomStairsBlock(VABlocks.COBBLED_SYENITE.defaultBlockState(), settings), Properties.ofFullCopy(Blocks.COBBLED_DEEPSLATE));
        COBBLED_SYENITE_SLAB = register("cobbled_syenite_slab", SlabBlock::new, Properties.ofFullCopy(Blocks.COBBLED_DEEPSLATE));
        COBBLED_SYENITE_WALL = register("cobbled_syenite_wall", WallBlock::new, Properties.ofFullCopy(Blocks.COBBLED_DEEPSLATE));
        POLISHED_SYENITE = register("polished_syenite", Block::new, Properties.ofFullCopy(Blocks.POLISHED_DEEPSLATE));
        POLISHED_SYENITE_STAIRS = register("polished_syenite_stairs", (settings) -> new CustomStairsBlock(POLISHED_SYENITE.defaultBlockState(), settings), Properties.ofFullCopy(Blocks.POLISHED_DEEPSLATE_STAIRS));
        POLISHED_SYENITE_SLAB = register("polished_syenite_slab", SlabBlock::new, Properties.ofFullCopy(Blocks.POLISHED_DEEPSLATE_SLAB));
        POLISHED_SYENITE_WALL = register("polished_syenite_wall", WallBlock::new, Properties.ofFullCopy(Blocks.POLISHED_DEEPSLATE_WALL));
        SYENITE_BRICKS = register("syenite_bricks", Block::new, Properties.ofFullCopy(Blocks.DEEPSLATE_BRICKS));
        CRACKED_SYENITE_BRICKS = register("cracked_syenite_bricks", Block::new, Properties.ofFullCopy(Blocks.DEEPSLATE_BRICKS));
        SYENITE_BRICK_STAIRS = register("syenite_brick_stairs", (settings) -> new CustomStairsBlock(VABlocks.SYENITE_BRICKS.defaultBlockState(), settings), Properties.ofFullCopy(Blocks.DEEPSLATE_BRICK_STAIRS));
        SYENITE_BRICK_SLAB = register("syenite_brick_slab", SlabBlock::new, Properties.ofFullCopy(Blocks.DEEPSLATE_BRICK_SLAB));
        SYENITE_BRICK_WALL = register("syenite_brick_wall", WallBlock::new, Properties.ofFullCopy(Blocks.DEEPSLATE_BRICK_WALL));
        CHISELED_SYENITE = register("chiseled_syenite", Block::new, Properties.ofFullCopy(VABlocks.SYENITE_BRICKS));

        ROCK_SALT_BLOCK = register("rock_salt_block", Block::new, Properties.ofFullCopy(Blocks.CALCITE));
        ROCK_SALT_CRYSTAL = register("rock_salt_crystal", CrystalBlock::new, Properties.ofFullCopy(Blocks.AMETHYST_CLUSTER).lightLevel(state -> 0).sound(SoundType.CALCITE).pushReaction(PushReaction.DESTROY));
        ROCK_SALT_ORE = register("rock_salt_ore", settings -> new DropExperienceBlock(UniformInt.of(0, 2), settings), BlockBehaviour.Properties.ofFullCopy(Blocks.IRON_ORE));
        DEEPSLATE_ROCK_SALT_ORE = register("deepslate_rock_salt_ore", settings -> new DropExperienceBlock(UniformInt.of(0, 2), settings), BlockBehaviour.Properties.ofFullCopy(Blocks.DEEPSLATE_IRON_ORE));

        ROCK_SALT_BRICKS = register("rock_salt_bricks", Block::new, Properties.ofFullCopy(ROCK_SALT_BLOCK).sound(SoundType.TUFF_BRICKS));
        ROCK_SALT_BRICK_STAIRS = register("rock_salt_brick_stairs", settings -> new StairBlock(ROCK_SALT_BRICKS.defaultBlockState(), settings), Properties.ofFullCopy(ROCK_SALT_BRICKS));
        ROCK_SALT_BRICK_SLAB = register("rock_salt_brick_slab", SlabBlock::new, Properties.ofFullCopy(ROCK_SALT_BRICKS));
        ROCK_SALT_BRICK_WALL = register("rock_salt_brick_wall", WallBlock::new, Properties.ofFullCopy(ROCK_SALT_BRICKS));
        CHISELED_ROCK_SALT_BRICKS = register("chiseled_rock_salt_bricks", Block::new, Properties.ofFullCopy(ROCK_SALT_BRICKS));

        SPOTLIGHT = register("spotlight", SpotlightBlock::new, Properties.ofFullCopy(STEEL_BLOCK).noOcclusion().lightLevel((state) -> state.getValue(SpotlightBlock.POWERED) ? 6 : 0));
        SPOTLIGHT_LIGHT = register("spotlight_light", SpotlightLightBlock::new, Properties.of().sound(SoundType.EMPTY).replaceable().noCollision().noLootTable().lightLevel((state) -> state.getValue(SpotlightLightBlock.LIT) ? 15 : 0).pushReaction(PushReaction.DESTROY));

        COTTON = register("cotton", CottonCropBlock::new, Properties.of().noCollision().randomTicks().instabreak().sound(SoundType.CROP));
        CORN_CROP = register("corn_crop", CornCropBlock::new, Properties.of().noCollision().randomTicks().instabreak().sound(SoundType.CROP).offsetType(BlockBehaviour.OffsetType.XZ));
        TOMATO = register("tomato", TomatoCropBlock::new, Properties.of().noCollision().randomTicks().instabreak().sound(SoundType.CROP));
        CABBAGE = register("cabbage", CabbageCropBlock::new, Properties.of().noCollision().randomTicks().instabreak().sound(SoundType.CROP));
        WISDOM_BERRY = register("wisdom_berry", WisdomBerryCropBlock::new, Properties.of().noCollision().randomTicks().instabreak().sound(SoundType.CROP));

        PORPHYRY = register("porphyry", Block::new, Properties.ofFullCopy(Blocks.TUFF));
        PORPHYRY_STAIRS = register("porphyry_stairs", (settings) -> new StairBlock(PORPHYRY.defaultBlockState(), settings), Properties.ofFullCopy(Blocks.TUFF));
        PORPHYRY_SLAB = register("porphyry_slab", SlabBlock::new, Properties.ofFullCopy(Blocks.TUFF));
        PORPHYRY_WALL = register("porphyry_wall", WallBlock::new, Properties.ofFullCopy(Blocks.TUFF));
        PORPHYRY_BRICKS = register("porphyry_bricks", Block::new, Properties.ofFullCopy(Blocks.TUFF_BRICKS));
        PORPHYRY_BRICK_STAIRS = register("porphyry_brick_stairs", (settings) -> new StairBlock(PORPHYRY_BRICKS.defaultBlockState(), settings), Properties.ofFullCopy(Blocks.TUFF_BRICKS));
        PORPHYRY_BRICK_SLAB = register("porphyry_brick_slab", SlabBlock::new, Properties.ofFullCopy(Blocks.TUFF_BRICKS));
        PORPHYRY_BRICK_WALL = register("porphyry_brick_wall", WallBlock::new, Properties.ofFullCopy(Blocks.TUFF_BRICKS));
        POLISHED_PORPHYRY = register("polished_porphyry", Block::new, Properties.ofFullCopy(Blocks.POLISHED_TUFF));
        POLISHED_PORPHYRY_STAIRS = register("polished_porphyry_stairs", (settings) -> new StairBlock(POLISHED_PORPHYRY.defaultBlockState(), settings), Properties.ofFullCopy(Blocks.POLISHED_TUFF));
        POLISHED_PORPHYRY_SLAB = register("polished_porphyry_slab", SlabBlock::new, Properties.ofFullCopy(Blocks.POLISHED_TUFF));
        POLISHED_PORPHYRY_WALL = register("polished_porphyry_wall", WallBlock::new, Properties.ofFullCopy(Blocks.POLISHED_TUFF));

        BALLOON_BULB = register("balloon_bulb", BalloonBulbBlock::new, Properties.ofFullCopy(COTTON).mapColor(MapColor.COLOR_LIGHT_BLUE).offsetType(BlockBehaviour.OffsetType.XZ));
        BALLOON_BULB_PLANT = register("balloon_bulb_plant", BalloonBulbPlantBlock::new, Properties.ofFullCopy(BALLOON_BULB).requiredFeatures(VirtualAdditions.PREVIEW));
        BALLOON_BULB_BUD = register("balloon_bulb_bud", BalloonBulbBudBlock::new, Properties.ofFullCopy(BALLOON_BULB).requiredFeatures(VirtualAdditions.PREVIEW));

        SMALL_SPRING_LOTUS = register("small_spring_lotus", SmallSpringLotusBlock::new, Properties.ofFullCopy(Blocks.SMALL_DRIPLEAF));
        POTTED_SMALL_SPRING_LOTUS = register("potted_small_spring_lotus", (settings) -> new FlowerPotBlock(SMALL_SPRING_LOTUS, settings), Properties.ofFullCopy(Blocks.FLOWER_POT));
        SPRING_LOTUS = register("spring_lotus", SpringLotusBlock::new, Properties.ofFullCopy(Blocks.BIG_DRIPLEAF));

        SOULBLOOM_LOG = register("soulbloom_log", RotatedPillarBlock::new, Properties.ofFullCopy(Blocks.CHERRY_LOG));
        SOULBLOOM_WOOD = register("soulbloom_wood", RotatedPillarBlock::new, Properties.ofFullCopy(Blocks.CHERRY_WOOD));
        STRIPPED_SOULBLOOM_LOG = register("stripped_soulbloom_log", RotatedPillarBlock::new, Properties.ofFullCopy(Blocks.STRIPPED_CHERRY_LOG));
        STRIPPED_SOULBLOOM_WOOD = register("stripped_soulbloom_wood", RotatedPillarBlock::new, Properties.ofFullCopy(Blocks.STRIPPED_CHERRY_WOOD));
        SOULBLOOM_PLANKS = register("soulbloom_planks", Block::new, Properties.ofFullCopy(Blocks.CHERRY_PLANKS));
        SOULBLOOM_STAIRS = register("soulbloom_stairs", (settings) -> new StairBlock(SOULBLOOM_PLANKS.defaultBlockState(), settings), Properties.ofFullCopy(Blocks.CHERRY_STAIRS));
        SOULBLOOM_SLAB = register("soulbloom_slab", SlabBlock::new, Properties.ofFullCopy(Blocks.CHERRY_SLAB));
        SOULBLOOM_FENCE = register("soulbloom_fence", FenceBlock::new, Properties.ofFullCopy(Blocks.CHERRY_SLAB));
        SOULBLOOM_FENCE_GATE = register("soulbloom_fence_gate", (settings) -> new FenceGateBlock(SOULBLOOM_WOODTYPE, settings), Properties.ofFullCopy(Blocks.CHERRY_SLAB));
        SOULBLOOM_DOOR = register("soulbloom_door", (settings) -> new DoorBlock( SOULBLOOM, settings), Properties.ofFullCopy(Blocks.CHERRY_DOOR));
        SOULBLOOM_TRAPDOOR = register("soulbloom_trapdoor", (settings) -> new TrapDoorBlock( SOULBLOOM, settings), Properties.ofFullCopy(Blocks.CHERRY_DOOR));
        SOULBLOOM_PRESSURE_PLATE = register("soulbloom_pressure_plate", (settings) -> new PressurePlateBlock(SOULBLOOM, settings), Properties.ofFullCopy(Blocks.CHERRY_BUTTON));
        SOULBLOOM_BUTTON = register("soulbloom_button", (settings) -> new ButtonBlock(SOULBLOOM, 30, settings), Properties.ofFullCopy(Blocks.CHERRY_BUTTON));
        SOULBLOOM_SIGN = register("soulbloom_sign", (settings) -> new CustomSignBlocks.CustomSignBlock(settings, SOULBLOOM_WOODTYPE), Properties.ofFullCopy(Blocks.CHERRY_SIGN));
        SOULBLOOM_WALL_SIGN = register("soulbloom_wall_sign", (settings) -> new CustomSignBlocks.CustomWallSignBlock(settings, SOULBLOOM_WOODTYPE), Properties.ofFullCopy(SOULBLOOM_SIGN).overrideLootTable(SOULBLOOM_SIGN.getLootTable()));
        SOULBLOOM_HANGING_SIGN = register("soulbloom_hanging_sign", (settings) -> new CustomSignBlocks.CustomHangingSignBlock(settings, SOULBLOOM_WOODTYPE), Properties.ofFullCopy(Blocks.CHERRY_HANGING_SIGN));
        SOULBLOOM_WALL_HANGING_SIGN = register("soulbloom_wall_hanging_sign", (settings) -> new CustomSignBlocks.CustomWallHangingSignBlock(settings, SOULBLOOM_WOODTYPE), Properties.ofFullCopy(Blocks.CHERRY_WALL_HANGING_SIGN).overrideLootTable(SOULBLOOM_HANGING_SIGN.getLootTable()));
        SOULBLOOM_SHELF = register("soulbloom_shelf", ShelfBlock::new, Properties.ofFullCopy(Blocks.CHERRY_SHELF));
        SOULBLOOM_LEAVES = register("soulbloom_leaves", (settings) -> new UntintedParticleLeavesBlock(0.1F, VAParticleTypes.SOULBLOOM_LEAVES, settings), Properties.ofFullCopy(Blocks.CHERRY_LEAVES));
        SOULBLOOM_SAPLING = register("soulbloom_sapling", (settings) -> new SaplingBlock(CustomSaplingGenerator.SOULBLOOM, settings), Properties.ofFullCopy(Blocks.CHERRY_SAPLING));
        POTTED_SOULBLOOM_SAPLING = register("potted_soulbloom_sapling", (settings) -> new FlowerPotBlock(SOULBLOOM_SAPLING, settings), Properties.ofFullCopy(Blocks.FLOWER_POT));

        BLUE_PETALS = register("blue_petals", FlowerBedBlock::new, Properties.of().mapColor(MapColor.PLANT).noCollision().sound(SoundType.PINK_PETALS).pushReaction(PushReaction.DESTROY));
        SOUL_SPROUT = register("soul_sprout", SoulSproutBlock::new, Properties.ofFullCopy(Blocks.FIREFLY_BUSH).mapColor(DyeColor.LIGHT_BLUE));
        POTTED_SOUL_SPROUT = register("potted_soul_sprout", (settings) -> new FlowerPotBlock(SOUL_SPROUT, settings), Properties.ofFullCopy(Blocks.FLOWER_POT));
        
        NECROTIC_NYLIUM = register("necrotic_nylium", (NecroticNyliumBlock::new), Properties.ofFullCopy(Blocks.WARPED_NYLIUM).mapColor(MapColor.COLOR_BLACK));
        NECROTIC_ROOTS = register("necrotic_roots", (RootsBlock::new), Properties.ofFullCopy(Blocks.WARPED_ROOTS).mapColor(MapColor.COLOR_BLACK));
        POTTED_NECROTIC_ROOTS = register("potted_necrotic_roots", (settings) -> new FlowerPotBlock(NECROTIC_ROOTS, settings), Properties.ofFullCopy(Blocks.FLOWER_POT));

        BONE_LITTER = register("bone_litter", LeafLitterBlock::new, Properties.of().mapColor(MapColor.SAND).noCollision().strength(0.2F).pushReaction(PushReaction.DESTROY).sound(SoundType.BONE_BLOCK));
        BONE_PILE = register("bone_pile", BonePileBlock::new, Properties.ofFullCopy(BONE_LITTER));

        WITHERED_LOG = register("withered_log", RotatedPillarBlock::new, Blocks.netherStemProperties(MapColor.COLOR_BLACK).strength(5.0F, 6.0F));
        WITHERED_WOOD = register("withered_wood", RotatedPillarBlock::new, Blocks.netherStemProperties(MapColor.COLOR_BLACK).strength(5.0F, 6.0F));
        STRIPPED_WITHERED_LOG = register("stripped_withered_log", RotatedPillarBlock::new, Blocks.netherStemProperties(MapColor.COLOR_BLACK).strength(5.0F, 6.0F));
        STRIPPED_WITHERED_WOOD = register("stripped_withered_wood", RotatedPillarBlock::new, Blocks.netherStemProperties(MapColor.COLOR_BLACK).strength(5.0F, 6.0F));
        WITHERED_PLANKS = register("withered_planks", Block::new, Properties.ofFullCopy(Blocks.WARPED_PLANKS).mapColor(MapColor.COLOR_BLACK).strength(5.0F, 6.0F));
        WITHERED_STAIRS = register("withered_stairs", (settings) -> new StairBlock(WITHERED_PLANKS.defaultBlockState(), settings), Properties.ofFullCopy(Blocks.WARPED_STAIRS).mapColor(MapColor.COLOR_BLACK).strength(5.0F, 6.0F));
        WITHERED_SLAB = register("withered_slab", SlabBlock::new, Properties.ofFullCopy(Blocks.WARPED_SLAB).mapColor(MapColor.COLOR_BLACK).strength(5.0F, 6.0F));
        WITHERED_FENCE = register("withered_fence", FenceBlock::new, Properties.ofFullCopy(Blocks.WARPED_FENCE).mapColor(MapColor.COLOR_BLACK).strength(5.0F, 6.0F));
        WITHERED_FENCE_GATE = register("withered_fence_gate", (settings) -> new FenceGateBlock(WITHERED_WOODTYPE, settings), Properties.ofFullCopy(Blocks.WARPED_FENCE_GATE).mapColor(MapColor.COLOR_BLACK).strength(5.0F, 6.0F));
        WITHERED_DOOR = register("withered_door", (settings) -> new DoorBlock( WITHERED, settings), Properties.ofFullCopy(Blocks.WARPED_DOOR).mapColor(MapColor.COLOR_BLACK).strength(5.0F, 6.0F));
        WITHERED_TRAPDOOR = register("withered_trapdoor", (settings) -> new TrapDoorBlock( WITHERED, settings), Properties.ofFullCopy(Blocks.WARPED_DOOR).mapColor(MapColor.COLOR_BLACK).strength(5.0F, 6.0F));
        WITHERED_PRESSURE_PLATE = register("withered_pressure_plate", (settings) -> new PressurePlateBlock(WITHERED, settings), Properties.ofFullCopy(Blocks.WARPED_PRESSURE_PLATE).strength(2.5F).mapColor(MapColor.COLOR_BLACK));
        WITHERED_BUTTON = register("withered_button", (settings) -> new ButtonBlock(WITHERED, 30, settings), Properties.ofFullCopy(Blocks.WARPED_BUTTON).strength(2.5F).mapColor(MapColor.COLOR_BLACK));
        WITHERED_SIGN = register("withered_sign", (settings) -> new CustomSignBlocks.CustomSignBlock(settings, WITHERED_WOODTYPE, DyeColor.WHITE), Properties.ofFullCopy(Blocks.WARPED_SIGN).strength(2.5F).mapColor(MapColor.COLOR_BLACK));
        WITHERED_WALL_SIGN = register("withered_wall_sign", (settings) -> new CustomSignBlocks.CustomWallSignBlock(settings, WITHERED_WOODTYPE, DyeColor.WHITE), Properties.ofFullCopy(Blocks.WARPED_SIGN).overrideLootTable(WITHERED_SIGN.getLootTable()).strength(2.5F).mapColor(MapColor.COLOR_BLACK));
        WITHERED_HANGING_SIGN = register("withered_hanging_sign", (settings) -> new CustomSignBlocks.CustomHangingSignBlock(settings, WITHERED_WOODTYPE, DyeColor.WHITE), Properties.ofFullCopy(Blocks.WARPED_HANGING_SIGN).strength(2.5F).mapColor(MapColor.COLOR_BLACK));
        WITHERED_WALL_HANGING_SIGN = register("withered_wall_hanging_sign", (settings) -> new CustomSignBlocks.CustomWallHangingSignBlock(settings, WITHERED_WOODTYPE, DyeColor.WHITE), Properties.ofFullCopy(Blocks.WARPED_HANGING_SIGN).overrideLootTable(WITHERED_HANGING_SIGN.getLootTable()).strength(2.5F).mapColor(MapColor.COLOR_BLACK));
        WITHERED_SHELF = register("withered_shelf", ShelfBlock::new, Properties.ofFullCopy(Blocks.WARPED_SHELF).strength(2.5F).mapColor(MapColor.COLOR_BLACK));
        WITHERED_LEAVES = register("withered_leaves", (settings) -> new UntintedParticleLeavesBlock(0.025F, ColorParticleOption.create(ParticleTypes.TINTED_LEAVES, 0x464928), settings), Properties.ofFullCopy(Blocks.CHERRY_LEAVES).sound(SoundType.MANGROVE_ROOTS).mapColor(MapColor.COLOR_BLACK));
        WITHERED_SAPLING = register("withered_sapling", (settings) -> new WitheredSaplingBlock(CustomSaplingGenerator.WITHERED, settings), Properties.ofFullCopy(Blocks.CHERRY_SAPLING).mapColor(MapColor.COLOR_BLACK));
        POTTED_WITHERED_SAPLING = register("potted_withered_sapling", (settings) -> new FlowerPotBlock(WITHERED_SAPLING, settings), Properties.ofFullCopy(Blocks.FLOWER_POT));

        SPECTRAL_FIRE = register("spectral_fire", SpectralFireBlock::new, Properties.ofFullCopy(Blocks.SOUL_FIRE).lightLevel((state) -> 11).mapColor(MapColor.SNOW));
        SPECTRAL_TORCH = register("spectral_torch", (settings -> new TorchBlock(VAParticleTypes.SPECTRAL_FLAME, settings)), Properties.ofFullCopy(Blocks.SOUL_TORCH).lightLevel((state) -> 11).mapColor(MapColor.SNOW));
        SPECTRAL_WALL_TORCH = register("spectral_wall_torch", (settings -> new WallTorchBlock(VAParticleTypes.SPECTRAL_FLAME, settings)), Properties.ofFullCopy(SPECTRAL_TORCH).overrideLootTable(SPECTRAL_TORCH.getLootTable()).overrideDescription(SPECTRAL_FIRE.getDescriptionId()));
        SPECTRAL_LANTERN = register("spectral_lantern", LanternBlock::new, Properties.ofFullCopy(Blocks.SOUL_LANTERN).lightLevel((state) -> 11));
        SPECTRAL_SAND = register("spectral_sand", settings -> new ColoredFallingBlock(new ColorRGBA(0xB3C1D0), settings), Properties.ofFullCopy(Blocks.SAND).isValidSpawn((state, world, pos, type) -> type.equals(VAEntityType.SPECTRE)).mapColor(MapColor.SNOW));

        OAK_HEDGE = register("oak_hedge", HedgeBlock::new, Properties.ofFullCopy(Blocks.OAK_LEAVES));
        SPRUCE_HEDGE = register("spruce_hedge", HedgeBlock::new, Properties.ofFullCopy(Blocks.SPRUCE_LEAVES));
        BIRCH_HEDGE = register("birch_hedge", HedgeBlock::new, Properties.ofFullCopy(Blocks.BIRCH_LEAVES));
        JUNGLE_HEDGE = register("jungle_hedge", HedgeBlock::new, Properties.ofFullCopy(Blocks.JUNGLE_LEAVES));
        ACACIA_HEDGE = register("acacia_hedge", HedgeBlock::new, Properties.ofFullCopy(Blocks.ACACIA_LEAVES));
        DARK_OAK_HEDGE = register("dark_oak_hedge", HedgeBlock::new, Properties.ofFullCopy(Blocks.DARK_OAK_LEAVES));
        PALE_OAK_HEDGE = register("pale_oak_hedge", HedgeBlock::new, Properties.ofFullCopy(Blocks.PALE_OAK_LEAVES));
        MANGROVE_HEDGE = register("mangrove_hedge", HedgeBlock::new, Properties.ofFullCopy(Blocks.MANGROVE_LEAVES));
        CHERRY_HEDGE = register("cherry_hedge", HedgeBlock::new, Properties.ofFullCopy(Blocks.CHERRY_LEAVES));
        SOULBLOOM_HEDGE = register("soulbloom_hedge", HedgeBlock::new, Properties.ofFullCopy(VABlocks.SOULBLOOM_LEAVES));
        WITHERED_HEDGE = register("withered_hedge", HedgeBlock::new, Properties.ofFullCopy(VABlocks.WITHERED_LEAVES));
        AZALEA_HEDGE = register("azalea_hedge", HedgeBlock::new, Properties.ofFullCopy(Blocks.AZALEA_LEAVES));
        FLOWERING_AZALEA_HEDGE = register("flowering_azalea_hedge", HedgeBlock::new, Properties.ofFullCopy(Blocks.FLOWERING_AZALEA_LEAVES));

        GLOWING_SILK = register("glowing_silk", HangingBlock::new, Properties.of().mapColor(MapColor.COLOR_LIGHT_BLUE).sound(SoundType.WART_BLOCK).lightLevel((state) -> 6).noCollision().noOcclusion().instabreak().offsetType(BlockBehaviour.OffsetType.XZ).ignitedByLava().pushReaction(PushReaction.DESTROY));
        FRAYED_SILK = register("frayed_silk", FrayedSilkBlock::new, Properties.of().mapColor(MapColor.WARPED_STEM).sound(SoundType.WART_BLOCK).noCollision().noOcclusion().instabreak().replaceable().offsetType(BlockBehaviour.OffsetType.XZ).ignitedByLava().pushReaction(PushReaction.DESTROY));
        LUMWASP_NEST = register("lumwasp_nest", LumwaspNestBlock::new, Properties.ofFullCopy(Blocks.HONEYCOMB_BLOCK).sound(SoundType.WART_BLOCK).mapColor(MapColor.WARPED_STEM).ignitedByLava());
        SILK_BLOCK = register("silk_block", SilkBlock::new, Properties.ofFullCopy(Blocks.HONEYCOMB_BLOCK).sound(SoundType.WART_BLOCK).mapColor(MapColor.WARPED_STEM).ignitedByLava());
        GREENCAP_MUSHROOM = register("greencap_mushroom", GreencapMushroomBlock::new, Properties.of().mapColor(MapColor.PLANT).noCollision().instabreak().sound(SoundType.NETHER_SPROUTS).offsetType(BlockBehaviour.OffsetType.XZ).lightLevel((state) -> 2).pushReaction(PushReaction.DESTROY));
        TALL_GREENCAP_MUSHROOMS = register("tall_greencap_mushrooms", TallGreencapMushroomBlock::new, Properties.of().mapColor(MapColor.PLANT).noCollision().instabreak().sound(SoundType.NETHER_SPROUTS).offsetType(BlockBehaviour.OffsetType.XZ).lightLevel((state) -> 5).pushReaction(PushReaction.DESTROY));
        POTTED_GREENCAP_MUSHROOM = register("potted_greencap_mushroom", (settings) -> new FlowerPotBlock(GREENCAP_MUSHROOM, settings), Properties.ofFullCopy(Blocks.FLOWER_POT));
        WEBBED_SILK = register("webbed_silk", SilkFluffBlock::new, Properties.of().strength(0.25F).sound(SoundType.POWDER_SNOW).mapColor(MapColor.WARPED_STEM).noOcclusion().isRedstoneConductor((state, world, pos) -> false).isSuffocating(((state, world, pos) -> false)).isViewBlocking((state, world, pos) -> false).ignitedByLava().isValidSpawn((state, world, pos, type) -> type == VAEntityType.LUMWASP));
        SILKBULB = register("silkbulb", Block::new, Properties.ofFullCopy(Blocks.SHROOMLIGHT).mapColor(MapColor.WARPED_STEM).lightLevel( (state) -> 15 ).ignitedByLava());
        WHITE_SILKBULB = register("white_silkbulb", Block::new, Properties.ofFullCopy(SILKBULB).mapColor(MapColor.SNOW));
        LIGHT_GRAY_SILKBULB = register("light_gray_silkbulb", Block::new, Properties.ofFullCopy(SILKBULB).mapColor(MapColor.COLOR_LIGHT_GRAY));
        GRAY_SILKBULB = register("gray_silkbulb", Block::new, Properties.ofFullCopy(SILKBULB).mapColor(MapColor.COLOR_GRAY));
        BLACK_SILKBULB = register("black_silkbulb", Block::new, Properties.ofFullCopy(SILKBULB).mapColor(MapColor.COLOR_BLACK));
        BROWN_SILKBULB = register("brown_silkbulb", Block::new, Properties.ofFullCopy(SILKBULB).mapColor(MapColor.COLOR_BROWN));
        RED_SILKBULB = register("red_silkbulb", Block::new, Properties.ofFullCopy(SILKBULB).mapColor(MapColor.COLOR_RED));
        ORANGE_SILKBULB = register("orange_silkbulb", Block::new, Properties.ofFullCopy(SILKBULB).mapColor(MapColor.COLOR_ORANGE));
        YELLOW_SILKBULB = register("yellow_silkbulb", Block::new, Properties.ofFullCopy(SILKBULB).mapColor(MapColor.COLOR_YELLOW));
        LIME_SILKBULB = register("lime_silkbulb", Block::new, Properties.ofFullCopy(SILKBULB).mapColor(MapColor.COLOR_LIGHT_GREEN));
        GREEN_SILKBULB = register("green_silkbulb", Block::new, Properties.ofFullCopy(SILKBULB).mapColor(MapColor.COLOR_GREEN));
        CYAN_SILKBULB = register("cyan_silkbulb", Block::new, Properties.ofFullCopy(SILKBULB).mapColor(MapColor.COLOR_CYAN));
        LIGHT_BLUE_SILKBULB = register("light_blue_silkbulb", Block::new, Properties.ofFullCopy(SILKBULB).mapColor(MapColor.COLOR_LIGHT_BLUE));
        BLUE_SILKBULB = register("blue_silkbulb", Block::new, Properties.ofFullCopy(SILKBULB).mapColor(MapColor.COLOR_BLUE));
        PURPLE_SILKBULB = register("purple_silkbulb", Block::new, Properties.ofFullCopy(SILKBULB).mapColor(MapColor.COLOR_PURPLE));
        MAGENTA_SILKBULB = register("magenta_silkbulb", Block::new, Properties.ofFullCopy(SILKBULB).mapColor(MapColor.COLOR_MAGENTA));
        PINK_SILKBULB = register("pink_silkbulb", Block::new, Properties.ofFullCopy(SILKBULB).mapColor(MapColor.COLOR_PINK));

        CHARTREUSE_WOOL = register("chartreuse_wool", Block::new, Properties.ofFullCopy(Blocks.WHITE_WOOL).mapColor(MapColor.COLOR_LIGHT_GREEN));
        CHARTREUSE_CARPET = register("chartreuse_carpet", (settings) -> new WoolCarpetBlock(VADyeColors.CHARTREUSE,  settings), Properties.ofFullCopy(Blocks.WHITE_CARPET).mapColor(MapColor.COLOR_LIGHT_GREEN));
        CHARTREUSE_TERRACOTTA = register("chartreuse_terracotta", Block::new, Properties.ofFullCopy(Blocks.WHITE_TERRACOTTA).mapColor(MapColor.COLOR_LIGHT_GREEN));
        CHARTREUSE_CONCRETE = register("chartreuse_concrete", Block::new, Properties.ofFullCopy(Blocks.WHITE_CONCRETE).mapColor(MapColor.COLOR_LIGHT_GREEN));
        CHARTREUSE_CONCRETE_POWDER = register("chartreuse_concrete_powder", (settings) -> new ConcretePowderBlock(CHARTREUSE_CONCRETE, settings), Properties.ofFullCopy(Blocks.WHITE_CONCRETE_POWDER).mapColor(MapColor.COLOR_LIGHT_GREEN));
        CHARTREUSE_STAINED_GLASS = register("chartreuse_stained_glass", (settings) -> new StainedGlassBlock(VADyeColors.CHARTREUSE, settings), Properties.ofFullCopy(Blocks.GLASS).mapColor(MapColor.COLOR_LIGHT_GREEN));
        CHARTREUSE_STAINED_GLASS_PANE = register("chartreuse_stained_glass_pane", (settings) -> new StainedGlassPaneBlock(VADyeColors.CHARTREUSE, settings), Properties.ofFullCopy(Blocks.GLASS_PANE).mapColor(MapColor.COLOR_LIGHT_GREEN));
        CHARTREUSE_SILKBULB = register("chartreuse_silkbulb", Block::new, Properties.ofFullCopy(SILKBULB).mapColor(MapColor.COLOR_LIGHT_GREEN));
        CHARTREUSE_CANDLE = register("chartreuse_candle", CandleBlock::new, Properties.ofFullCopy(Blocks.CANDLE).mapColor(MapColor.COLOR_LIGHT_GREEN));
        CHARTREUSE_CANDLE_CAKE = register("chartreuse_candle_cake", (settings) -> new CandleCakeBlock(CHARTREUSE_CANDLE, settings), Properties.ofFullCopy(Blocks.CANDLE_CAKE).mapColor(MapColor.COLOR_LIGHT_GREEN));
        CHARTREUSE_BED = register("chartreuse_bed", (settings) -> new CustomBedBlock(VADyeColors.CHARTREUSE, settings), Properties.ofFullCopy(Blocks.WHITE_BED));
        CHARTREUSE_SHULKER_BOX = register("chartreuse_shulker_box", (settings) -> new CustomShulkerBoxBlock(VADyeColors.CHARTREUSE, settings), Properties.ofFullCopy(Blocks.SHULKER_BOX));
        CHARTREUSE_BANNER = register("chartreuse_banner", (settings) -> new CustomBannerBlock(VADyeColors.CHARTREUSE, settings), Properties.ofFullCopy(Blocks.WHITE_BANNER));
        CHARTREUSE_WALL_BANNER = register("chartreuse_wall_banner", (settings) -> new CustomWallBannerBlock(VADyeColors.CHARTREUSE, settings), Properties.ofFullCopy(Blocks.WHITE_WALL_BANNER).overrideLootTable(CHARTREUSE_BANNER.getLootTable()));
        CHARTREUSE_GLAZED_TERRACOTTA = register("chartreuse_glazed_terracotta", GlazedTerracottaBlock::new, Properties.ofFullCopy(Blocks.WHITE_GLAZED_TERRACOTTA).mapColor(VADyeColors.CHARTREUSE));
        
        MAROON_WOOL = register("maroon_wool", Block::new, Properties.ofFullCopy(Blocks.WHITE_WOOL).mapColor(MapColor.COLOR_LIGHT_GREEN));
        MAROON_CARPET = register("maroon_carpet", (settings) -> new WoolCarpetBlock(VADyeColors.MAROON,  settings), Properties.ofFullCopy(Blocks.WHITE_CARPET).mapColor(MapColor.COLOR_LIGHT_GREEN));
        MAROON_TERRACOTTA = register("maroon_terracotta", Block::new, Properties.ofFullCopy(Blocks.WHITE_TERRACOTTA).mapColor(MapColor.COLOR_LIGHT_GREEN));
        MAROON_CONCRETE = register("maroon_concrete", Block::new, Properties.ofFullCopy(Blocks.WHITE_CONCRETE).mapColor(MapColor.COLOR_LIGHT_GREEN));
        MAROON_CONCRETE_POWDER = register("maroon_concrete_powder", (settings) -> new ConcretePowderBlock(MAROON_CONCRETE, settings), Properties.ofFullCopy(Blocks.WHITE_CONCRETE_POWDER).mapColor(MapColor.COLOR_LIGHT_GREEN));
        MAROON_STAINED_GLASS = register("maroon_stained_glass", (settings) -> new StainedGlassBlock(VADyeColors.MAROON, settings), Properties.ofFullCopy(Blocks.GLASS).mapColor(MapColor.COLOR_LIGHT_GREEN));
        MAROON_STAINED_GLASS_PANE = register("maroon_stained_glass_pane", (settings) -> new StainedGlassPaneBlock(VADyeColors.MAROON, settings), Properties.ofFullCopy(Blocks.GLASS_PANE).mapColor(MapColor.COLOR_LIGHT_GREEN));
        MAROON_SILKBULB = register("maroon_silkbulb", Block::new, Properties.ofFullCopy(SILKBULB).mapColor(MapColor.COLOR_LIGHT_GREEN));
        MAROON_CANDLE = register("maroon_candle", CandleBlock::new, Properties.ofFullCopy(Blocks.CANDLE).mapColor(MapColor.COLOR_LIGHT_GREEN));
        MAROON_CANDLE_CAKE = register("maroon_candle_cake", (settings) -> new CandleCakeBlock(MAROON_CANDLE, settings), Properties.ofFullCopy(Blocks.CANDLE_CAKE).mapColor(MapColor.COLOR_LIGHT_GREEN));
        MAROON_BED = register("maroon_bed", (settings) -> new CustomBedBlock(VADyeColors.MAROON, settings), Properties.ofFullCopy(Blocks.WHITE_BED));
        MAROON_SHULKER_BOX = register("maroon_shulker_box", (settings) -> new CustomShulkerBoxBlock(VADyeColors.MAROON, settings), Properties.ofFullCopy(Blocks.SHULKER_BOX));
        MAROON_BANNER = register("maroon_banner", (settings) -> new CustomBannerBlock(VADyeColors.MAROON, settings), Properties.ofFullCopy(Blocks.WHITE_BANNER));
        MAROON_WALL_BANNER = register("maroon_wall_banner", (settings) -> new CustomWallBannerBlock(VADyeColors.MAROON, settings), Properties.ofFullCopy(Blocks.WHITE_WALL_BANNER).overrideLootTable(MAROON_BANNER.getLootTable()));
        MAROON_GLAZED_TERRACOTTA = register("maroon_glazed_terracotta", GlazedTerracottaBlock::new, Properties.ofFullCopy(Blocks.WHITE_GLAZED_TERRACOTTA).mapColor(VADyeColors.MAROON));

        INDIGO_WOOL = register("indigo_wool", Block::new, Properties.ofFullCopy(Blocks.WHITE_WOOL).mapColor(MapColor.COLOR_LIGHT_GREEN));
        INDIGO_CARPET = register("indigo_carpet", (settings) -> new WoolCarpetBlock(VADyeColors.INDIGO,  settings), Properties.ofFullCopy(Blocks.WHITE_CARPET).mapColor(MapColor.COLOR_LIGHT_GREEN));
        INDIGO_TERRACOTTA = register("indigo_terracotta", Block::new, Properties.ofFullCopy(Blocks.WHITE_TERRACOTTA).mapColor(MapColor.COLOR_LIGHT_GREEN));
        INDIGO_CONCRETE = register("indigo_concrete", Block::new, Properties.ofFullCopy(Blocks.WHITE_CONCRETE).mapColor(MapColor.COLOR_LIGHT_GREEN));
        INDIGO_CONCRETE_POWDER = register("indigo_concrete_powder", (settings) -> new ConcretePowderBlock(INDIGO_CONCRETE, settings), Properties.ofFullCopy(Blocks.WHITE_CONCRETE_POWDER).mapColor(MapColor.COLOR_LIGHT_GREEN));
        INDIGO_STAINED_GLASS = register("indigo_stained_glass", (settings) -> new StainedGlassBlock(VADyeColors.INDIGO, settings), Properties.ofFullCopy(Blocks.GLASS).mapColor(MapColor.COLOR_LIGHT_GREEN));
        INDIGO_STAINED_GLASS_PANE = register("indigo_stained_glass_pane", (settings) -> new StainedGlassPaneBlock(VADyeColors.INDIGO, settings), Properties.ofFullCopy(Blocks.GLASS_PANE).mapColor(MapColor.COLOR_LIGHT_GREEN));
        INDIGO_SILKBULB = register("indigo_silkbulb", Block::new, Properties.ofFullCopy(SILKBULB).mapColor(MapColor.COLOR_LIGHT_GREEN));
        INDIGO_CANDLE = register("indigo_candle", CandleBlock::new, Properties.ofFullCopy(Blocks.CANDLE).mapColor(MapColor.COLOR_LIGHT_GREEN));
        INDIGO_CANDLE_CAKE = register("indigo_candle_cake", (settings) -> new CandleCakeBlock(INDIGO_CANDLE, settings), Properties.ofFullCopy(Blocks.CANDLE_CAKE).mapColor(MapColor.COLOR_LIGHT_GREEN));
        INDIGO_BED = register("indigo_bed", (settings) -> new CustomBedBlock(VADyeColors.INDIGO, settings), Properties.ofFullCopy(Blocks.WHITE_BED));
        INDIGO_SHULKER_BOX = register("indigo_shulker_box", (settings) -> new CustomShulkerBoxBlock(VADyeColors.INDIGO, settings), Properties.ofFullCopy(Blocks.SHULKER_BOX));
        INDIGO_BANNER = register("indigo_banner", (settings) -> new CustomBannerBlock(VADyeColors.INDIGO, settings), Properties.ofFullCopy(Blocks.WHITE_BANNER));
        INDIGO_WALL_BANNER = register("indigo_wall_banner", (settings) -> new CustomWallBannerBlock(VADyeColors.INDIGO, settings), Properties.ofFullCopy(Blocks.WHITE_WALL_BANNER).overrideLootTable(INDIGO_BANNER.getLootTable()));
        INDIGO_GLAZED_TERRACOTTA = register("indigo_glazed_terracotta", GlazedTerracottaBlock::new, Properties.ofFullCopy(Blocks.WHITE_GLAZED_TERRACOTTA).mapColor(VADyeColors.INDIGO));

        PLUM_WOOL = register("plum_wool", Block::new, Properties.ofFullCopy(Blocks.WHITE_WOOL).mapColor(MapColor.COLOR_LIGHT_GREEN));
        PLUM_CARPET = register("plum_carpet", (settings) -> new WoolCarpetBlock(VADyeColors.PLUM,  settings), Properties.ofFullCopy(Blocks.WHITE_CARPET).mapColor(MapColor.COLOR_LIGHT_GREEN));
        PLUM_TERRACOTTA = register("plum_terracotta", Block::new, Properties.ofFullCopy(Blocks.WHITE_TERRACOTTA).mapColor(MapColor.COLOR_LIGHT_GREEN));
        PLUM_CONCRETE = register("plum_concrete", Block::new, Properties.ofFullCopy(Blocks.WHITE_CONCRETE).mapColor(MapColor.COLOR_LIGHT_GREEN));
        PLUM_CONCRETE_POWDER = register("plum_concrete_powder", (settings) -> new ConcretePowderBlock(PLUM_CONCRETE, settings), Properties.ofFullCopy(Blocks.WHITE_CONCRETE_POWDER).mapColor(MapColor.COLOR_LIGHT_GREEN));
        PLUM_STAINED_GLASS = register("plum_stained_glass", (settings) -> new StainedGlassBlock(VADyeColors.PLUM, settings), Properties.ofFullCopy(Blocks.GLASS).mapColor(MapColor.COLOR_LIGHT_GREEN));
        PLUM_STAINED_GLASS_PANE = register("plum_stained_glass_pane", (settings) -> new StainedGlassPaneBlock(VADyeColors.PLUM, settings), Properties.ofFullCopy(Blocks.GLASS_PANE).mapColor(MapColor.COLOR_LIGHT_GREEN));
        PLUM_SILKBULB = register("plum_silkbulb", Block::new, Properties.ofFullCopy(SILKBULB).mapColor(MapColor.COLOR_LIGHT_GREEN));
        PLUM_CANDLE = register("plum_candle", CandleBlock::new, Properties.ofFullCopy(Blocks.CANDLE).mapColor(MapColor.COLOR_LIGHT_GREEN));
        PLUM_CANDLE_CAKE = register("plum_candle_cake", (settings) -> new CandleCakeBlock(PLUM_CANDLE, settings), Properties.ofFullCopy(Blocks.CANDLE_CAKE).mapColor(MapColor.COLOR_LIGHT_GREEN));
        PLUM_BED = register("plum_bed", (settings) -> new CustomBedBlock(VADyeColors.PLUM, settings), Properties.ofFullCopy(Blocks.WHITE_BED));
        PLUM_SHULKER_BOX = register("plum_shulker_box", (settings) -> new CustomShulkerBoxBlock(VADyeColors.PLUM, settings), Properties.ofFullCopy(Blocks.SHULKER_BOX));
        PLUM_BANNER = register("plum_banner", (settings) -> new CustomBannerBlock(VADyeColors.PLUM, settings), Properties.ofFullCopy(Blocks.WHITE_BANNER));
        PLUM_WALL_BANNER = register("plum_wall_banner", (settings) -> new CustomWallBannerBlock(VADyeColors.PLUM, settings), Properties.ofFullCopy(Blocks.WHITE_WALL_BANNER).overrideLootTable(PLUM_BANNER.getLootTable()));
        PLUM_GLAZED_TERRACOTTA = register("plum_glazed_terracotta", GlazedTerracottaBlock::new, Properties.ofFullCopy(Blocks.WHITE_GLAZED_TERRACOTTA).mapColor(VADyeColors.PLUM));

        VIRIDIAN_WOOL = register("viridian_wool", Block::new, Properties.ofFullCopy(Blocks.WHITE_WOOL).mapColor(MapColor.COLOR_LIGHT_GREEN));
        VIRIDIAN_CARPET = register("viridian_carpet", (settings) -> new WoolCarpetBlock(VADyeColors.VIRIDIAN,  settings), Properties.ofFullCopy(Blocks.WHITE_CARPET).mapColor(MapColor.COLOR_LIGHT_GREEN));
        VIRIDIAN_TERRACOTTA = register("viridian_terracotta", Block::new, Properties.ofFullCopy(Blocks.WHITE_TERRACOTTA).mapColor(MapColor.COLOR_LIGHT_GREEN));
        VIRIDIAN_CONCRETE = register("viridian_concrete", Block::new, Properties.ofFullCopy(Blocks.WHITE_CONCRETE).mapColor(MapColor.COLOR_LIGHT_GREEN));
        VIRIDIAN_CONCRETE_POWDER = register("viridian_concrete_powder", (settings) -> new ConcretePowderBlock(VIRIDIAN_CONCRETE, settings), Properties.ofFullCopy(Blocks.WHITE_CONCRETE_POWDER).mapColor(MapColor.COLOR_LIGHT_GREEN));
        VIRIDIAN_STAINED_GLASS = register("viridian_stained_glass", (settings) -> new StainedGlassBlock(VADyeColors.VIRIDIAN, settings), Properties.ofFullCopy(Blocks.GLASS).mapColor(MapColor.COLOR_LIGHT_GREEN));
        VIRIDIAN_STAINED_GLASS_PANE = register("viridian_stained_glass_pane", (settings) -> new StainedGlassPaneBlock(VADyeColors.VIRIDIAN, settings), Properties.ofFullCopy(Blocks.GLASS_PANE).mapColor(MapColor.COLOR_LIGHT_GREEN));
        VIRIDIAN_SILKBULB = register("viridian_silkbulb", Block::new, Properties.ofFullCopy(SILKBULB).mapColor(MapColor.COLOR_LIGHT_GREEN));
        VIRIDIAN_CANDLE = register("viridian_candle", CandleBlock::new, Properties.ofFullCopy(Blocks.CANDLE).mapColor(MapColor.COLOR_LIGHT_GREEN));
        VIRIDIAN_CANDLE_CAKE = register("viridian_candle_cake", (settings) -> new CandleCakeBlock(VIRIDIAN_CANDLE, settings), Properties.ofFullCopy(Blocks.CANDLE_CAKE).mapColor(MapColor.COLOR_LIGHT_GREEN));
        VIRIDIAN_BED = register("viridian_bed", (settings) -> new CustomBedBlock(VADyeColors.VIRIDIAN, settings), Properties.ofFullCopy(Blocks.WHITE_BED));
        VIRIDIAN_SHULKER_BOX = register("viridian_shulker_box", (settings) -> new CustomShulkerBoxBlock(VADyeColors.VIRIDIAN, settings), Properties.ofFullCopy(Blocks.SHULKER_BOX));
        VIRIDIAN_BANNER = register("viridian_banner", (settings) -> new CustomBannerBlock(VADyeColors.VIRIDIAN, settings), Properties.ofFullCopy(Blocks.WHITE_BANNER));
        VIRIDIAN_WALL_BANNER = register("viridian_wall_banner", (settings) -> new CustomWallBannerBlock(VADyeColors.VIRIDIAN, settings), Properties.ofFullCopy(Blocks.WHITE_WALL_BANNER).overrideLootTable(VIRIDIAN_BANNER.getLootTable()));
        VIRIDIAN_GLAZED_TERRACOTTA = register("viridian_glazed_terracotta", GlazedTerracottaBlock::new, Properties.ofFullCopy(Blocks.WHITE_GLAZED_TERRACOTTA).mapColor(VADyeColors.VIRIDIAN));

        TAN_WOOL = register("tan_wool", Block::new, Properties.ofFullCopy(Blocks.WHITE_WOOL).mapColor(MapColor.COLOR_LIGHT_GREEN));
        TAN_CARPET = register("tan_carpet", (settings) -> new WoolCarpetBlock(VADyeColors.TAN,  settings), Properties.ofFullCopy(Blocks.WHITE_CARPET).mapColor(MapColor.COLOR_LIGHT_GREEN));
        TAN_TERRACOTTA = register("tan_terracotta", Block::new, Properties.ofFullCopy(Blocks.WHITE_TERRACOTTA).mapColor(MapColor.COLOR_LIGHT_GREEN));
        TAN_CONCRETE = register("tan_concrete", Block::new, Properties.ofFullCopy(Blocks.WHITE_CONCRETE).mapColor(MapColor.COLOR_LIGHT_GREEN));
        TAN_CONCRETE_POWDER = register("tan_concrete_powder", (settings) -> new ConcretePowderBlock(TAN_CONCRETE, settings), Properties.ofFullCopy(Blocks.WHITE_CONCRETE_POWDER).mapColor(MapColor.COLOR_LIGHT_GREEN));
        TAN_STAINED_GLASS = register("tan_stained_glass", (settings) -> new StainedGlassBlock(VADyeColors.TAN, settings), Properties.ofFullCopy(Blocks.GLASS).mapColor(MapColor.COLOR_LIGHT_GREEN));
        TAN_STAINED_GLASS_PANE = register("tan_stained_glass_pane", (settings) -> new StainedGlassPaneBlock(VADyeColors.TAN, settings), Properties.ofFullCopy(Blocks.GLASS_PANE).mapColor(MapColor.COLOR_LIGHT_GREEN));
        TAN_SILKBULB = register("tan_silkbulb", Block::new, Properties.ofFullCopy(SILKBULB).mapColor(MapColor.COLOR_LIGHT_GREEN));
        TAN_CANDLE = register("tan_candle", CandleBlock::new, Properties.ofFullCopy(Blocks.CANDLE).mapColor(MapColor.COLOR_LIGHT_GREEN));
        TAN_CANDLE_CAKE = register("tan_candle_cake", (settings) -> new CandleCakeBlock(TAN_CANDLE, settings), Properties.ofFullCopy(Blocks.CANDLE_CAKE).mapColor(MapColor.COLOR_LIGHT_GREEN));
        TAN_BED = register("tan_bed", (settings) -> new CustomBedBlock(VADyeColors.TAN, settings), Properties.ofFullCopy(Blocks.WHITE_BED));
        TAN_SHULKER_BOX = register("tan_shulker_box", (settings) -> new CustomShulkerBoxBlock(VADyeColors.TAN, settings), Properties.ofFullCopy(Blocks.SHULKER_BOX));
        TAN_BANNER = register("tan_banner", (settings) -> new CustomBannerBlock(VADyeColors.TAN, settings), Properties.ofFullCopy(Blocks.WHITE_BANNER));
        TAN_WALL_BANNER = register("tan_wall_banner", (settings) -> new CustomWallBannerBlock(VADyeColors.TAN, settings), Properties.ofFullCopy(Blocks.WHITE_WALL_BANNER).overrideLootTable(TAN_BANNER.getLootTable()));
        TAN_GLAZED_TERRACOTTA = register("tan_glazed_terracotta", GlazedTerracottaBlock::new, Properties.ofFullCopy(Blocks.WHITE_GLAZED_TERRACOTTA).mapColor(VADyeColors.TAN));

        SINOPIA_WOOL = register("sinopia_wool", Block::new, Properties.ofFullCopy(Blocks.WHITE_WOOL).mapColor(MapColor.COLOR_LIGHT_GREEN));
        SINOPIA_CARPET = register("sinopia_carpet", (settings) -> new WoolCarpetBlock(VADyeColors.SINOPIA,  settings), Properties.ofFullCopy(Blocks.WHITE_CARPET).mapColor(MapColor.COLOR_LIGHT_GREEN));
        SINOPIA_TERRACOTTA = register("sinopia_terracotta", Block::new, Properties.ofFullCopy(Blocks.WHITE_TERRACOTTA).mapColor(MapColor.COLOR_LIGHT_GREEN));
        SINOPIA_CONCRETE = register("sinopia_concrete", Block::new, Properties.ofFullCopy(Blocks.WHITE_CONCRETE).mapColor(MapColor.COLOR_LIGHT_GREEN));
        SINOPIA_CONCRETE_POWDER = register("sinopia_concrete_powder", (settings) -> new ConcretePowderBlock(SINOPIA_CONCRETE, settings), Properties.ofFullCopy(Blocks.WHITE_CONCRETE_POWDER).mapColor(MapColor.COLOR_LIGHT_GREEN));
        SINOPIA_STAINED_GLASS = register("sinopia_stained_glass", (settings) -> new StainedGlassBlock(VADyeColors.SINOPIA, settings), Properties.ofFullCopy(Blocks.GLASS).mapColor(MapColor.COLOR_LIGHT_GREEN));
        SINOPIA_STAINED_GLASS_PANE = register("sinopia_stained_glass_pane", (settings) -> new StainedGlassPaneBlock(VADyeColors.SINOPIA, settings), Properties.ofFullCopy(Blocks.GLASS_PANE).mapColor(MapColor.COLOR_LIGHT_GREEN));
        SINOPIA_SILKBULB = register("sinopia_silkbulb", Block::new, Properties.ofFullCopy(SILKBULB).mapColor(MapColor.COLOR_LIGHT_GREEN));
        SINOPIA_CANDLE = register("sinopia_candle", CandleBlock::new, Properties.ofFullCopy(Blocks.CANDLE).mapColor(MapColor.COLOR_LIGHT_GREEN));
        SINOPIA_CANDLE_CAKE = register("sinopia_candle_cake", (settings) -> new CandleCakeBlock(SINOPIA_CANDLE, settings), Properties.ofFullCopy(Blocks.CANDLE_CAKE).mapColor(MapColor.COLOR_LIGHT_GREEN));
        SINOPIA_BED = register("sinopia_bed", (settings) -> new CustomBedBlock(VADyeColors.SINOPIA, settings), Properties.ofFullCopy(Blocks.WHITE_BED));
        SINOPIA_SHULKER_BOX = register("sinopia_shulker_box", (settings) -> new CustomShulkerBoxBlock(VADyeColors.SINOPIA, settings), Properties.ofFullCopy(Blocks.SHULKER_BOX));
        SINOPIA_BANNER = register("sinopia_banner", (settings) -> new CustomBannerBlock(VADyeColors.SINOPIA, settings), Properties.ofFullCopy(Blocks.WHITE_BANNER));
        SINOPIA_WALL_BANNER = register("sinopia_wall_banner", (settings) -> new CustomWallBannerBlock(VADyeColors.SINOPIA, settings), Properties.ofFullCopy(Blocks.WHITE_WALL_BANNER).overrideLootTable(SINOPIA_BANNER.getLootTable()));
        SINOPIA_GLAZED_TERRACOTTA = register("sinopia_glazed_terracotta", GlazedTerracottaBlock::new, Properties.ofFullCopy(Blocks.WHITE_GLAZED_TERRACOTTA).mapColor(VADyeColors.SINOPIA));

        LILAC_WOOL = register("lilac_wool", Block::new, Properties.ofFullCopy(Blocks.WHITE_WOOL).mapColor(MapColor.COLOR_LIGHT_GREEN));
        LILAC_CARPET = register("lilac_carpet", (settings) -> new WoolCarpetBlock(VADyeColors.LILAC,  settings), Properties.ofFullCopy(Blocks.WHITE_CARPET).mapColor(MapColor.COLOR_LIGHT_GREEN));
        LILAC_TERRACOTTA = register("lilac_terracotta", Block::new, Properties.ofFullCopy(Blocks.WHITE_TERRACOTTA).mapColor(MapColor.COLOR_LIGHT_GREEN));
        LILAC_CONCRETE = register("lilac_concrete", Block::new, Properties.ofFullCopy(Blocks.WHITE_CONCRETE).mapColor(MapColor.COLOR_LIGHT_GREEN));
        LILAC_CONCRETE_POWDER = register("lilac_concrete_powder", (settings) -> new ConcretePowderBlock(LILAC_CONCRETE, settings), Properties.ofFullCopy(Blocks.WHITE_CONCRETE_POWDER).mapColor(MapColor.COLOR_LIGHT_GREEN));
        LILAC_STAINED_GLASS = register("lilac_stained_glass", (settings) -> new StainedGlassBlock(VADyeColors.LILAC, settings), Properties.ofFullCopy(Blocks.GLASS).mapColor(MapColor.COLOR_LIGHT_GREEN));
        LILAC_STAINED_GLASS_PANE = register("lilac_stained_glass_pane", (settings) -> new StainedGlassPaneBlock(VADyeColors.LILAC, settings), Properties.ofFullCopy(Blocks.GLASS_PANE).mapColor(MapColor.COLOR_LIGHT_GREEN));
        LILAC_SILKBULB = register("lilac_silkbulb", Block::new, Properties.ofFullCopy(SILKBULB).mapColor(MapColor.COLOR_LIGHT_GREEN));
        LILAC_CANDLE = register("lilac_candle", CandleBlock::new, Properties.ofFullCopy(Blocks.CANDLE).mapColor(MapColor.COLOR_LIGHT_GREEN));
        LILAC_CANDLE_CAKE = register("lilac_candle_cake", (settings) -> new CandleCakeBlock(LILAC_CANDLE, settings), Properties.ofFullCopy(Blocks.CANDLE_CAKE).mapColor(MapColor.COLOR_LIGHT_GREEN));
        LILAC_BED = register("lilac_bed", (settings) -> new CustomBedBlock(VADyeColors.LILAC, settings), Properties.ofFullCopy(Blocks.WHITE_BED));
        LILAC_SHULKER_BOX = register("lilac_shulker_box", (settings) -> new CustomShulkerBoxBlock(VADyeColors.LILAC, settings), Properties.ofFullCopy(Blocks.SHULKER_BOX));
        LILAC_BANNER = register("lilac_banner", (settings) -> new CustomBannerBlock(VADyeColors.LILAC, settings), Properties.ofFullCopy(Blocks.WHITE_BANNER));
        LILAC_WALL_BANNER = register("lilac_wall_banner", (settings) -> new CustomWallBannerBlock(VADyeColors.LILAC, settings), Properties.ofFullCopy(Blocks.WHITE_WALL_BANNER).overrideLootTable(LILAC_BANNER.getLootTable()));
        LILAC_GLAZED_TERRACOTTA = register("lilac_glazed_terracotta", GlazedTerracottaBlock::new, Properties.ofFullCopy(Blocks.WHITE_GLAZED_TERRACOTTA).mapColor(VADyeColors.LILAC));

        COLORING_STATION = register("coloring_station", ColoringStationBlock::new, Properties.ofFullCopy(Blocks.SMITHING_TABLE));

        ACID = register("acid", (settings) -> new AcidFluidBlock(VAFluids.ACID, settings), Properties.of().mapColor(MapColor.COLOR_LIGHT_GREEN).lightLevel(((state) -> 6)).sound(SoundType.EMPTY).replaceable().noCollision().strength(100.0F).noLootTable().isValidSpawn(((state, world, pos, type) -> type == VAEntityType.LUMWASP)).pushReaction(PushReaction.DESTROY));
        ACID_BLOCK = register("acid_block", AcidBlock::new, Properties.of().mapColor(MapColor.COLOR_LIGHT_GREEN).instabreak().sound(SoundType.HONEY_BLOCK).noOcclusion().isRedstoneConductor((state, world, pos) -> false));

        IOLITE_ORE = register("iolite_ore", (settings) -> new DropExperienceBlock(UniformInt.of(5, 9), settings), Properties.ofFullCopy(Blocks.END_STONE).strength(4.5F, 4.5F).requiresCorrectToolForDrops());
        IOLITE_BLOCK = register("iolite_block", Block::new, Properties.of().mapColor(MapColor.COLOR_MAGENTA).sound(SoundType.METAL).requiresCorrectToolForDrops().destroyTime(5.0F).explosionResistance(300.0F));
        MINI_PORTAL = register("mini_portal", MiniPortalBlock::new, Properties.ofFullCopy(Blocks.GLASS).lightLevel(state -> 11));
        ENTANGLEMENT_DRIVE = register("entanglement_drive", EntanglementDriveBlock::new, Properties.of().noOcclusion().sound(SoundType.NETHERITE_BLOCK).lightLevel(state -> 3).destroyTime(22.5F).requiresCorrectToolForDrops().explosionResistance(600.0F));
        REMOTE_NOTIFIER = register("remote_notifier", RemoteNotifierBlock::new, Properties.of().noOcclusion().sound(SoundType.NETHERITE_BLOCK).destroyTime(22.5F).requiresCorrectToolForDrops().explosionResistance(600.0F).requiredFeatures(VirtualAdditions.PREVIEW));

        DESTRUCTIVE_SCULK = register("destructive_sculk", DestructiveSculkBlock::new, Properties.ofFullCopy(Blocks.SCULK));

        setBlocksInitialized();
    }

    public static void init(){
        LandPathNodeTypesRegistry.register(ACID, PathType.DAMAGE_OTHER, PathType.DAMAGE_OTHER);
        LandPathNodeTypesRegistry.register(SPRING_LOTUS, PathType.DAMAGE_OTHER, PathType.DAMAGE_OTHER);

        FireBlock fire = (FireBlock) Blocks.FIRE;
        fire.setFlammable(CLIMBING_ROPE_ANCHOR, 5, 20);
        fire.setFlammable(CLIMBING_ROPE, 5, 20);
        fire.setFlammable(SOULBLOOM_LOG, 5, 20);
        fire.setFlammable(SOULBLOOM_WOOD, 5, 20);
        fire.setFlammable(STRIPPED_SOULBLOOM_LOG, 5, 20);
        fire.setFlammable(STRIPPED_SOULBLOOM_WOOD, 5, 20);
        fire.setFlammable(SOULBLOOM_PLANKS, 5, 20);
        fire.setFlammable(SOULBLOOM_STAIRS, 5, 20);
        fire.setFlammable(SOULBLOOM_SLAB, 5, 20);
        fire.setFlammable(SOULBLOOM_FENCE, 5, 20);
        fire.setFlammable(SOULBLOOM_LEAVES, 30, 60);
        fire.setFlammable(SOULBLOOM_HEDGE, 30, 60);
        fire.setFlammable(OAK_HEDGE, 30, 60);
        fire.setFlammable(SPRUCE_HEDGE, 30, 60);
        fire.setFlammable(BIRCH_HEDGE, 30, 60);
        fire.setFlammable(JUNGLE_HEDGE, 30, 60);
        fire.setFlammable(ACACIA_HEDGE, 30, 60);
        fire.setFlammable(DARK_OAK_HEDGE, 30, 60);
        fire.setFlammable(PALE_OAK_HEDGE, 30, 60);
        fire.setFlammable(MANGROVE_HEDGE, 30, 60);
        fire.setFlammable(CHERRY_HEDGE, 30, 60);
        fire.setFlammable(AZALEA_HEDGE, 30, 60);
        fire.setFlammable(FLOWERING_AZALEA_HEDGE, 30, 60);
        fire.setFlammable(GLOWING_SILK, 30, 60);
        fire.setFlammable(FRAYED_SILK, 30, 60);
        fire.setFlammable(LUMWASP_NEST, 5, 20);
        fire.setFlammable(SILK_BLOCK, 5, 20);
        fire.setFlammable(WEBBED_SILK, 30, 60);
        fire.setFlammable(SILKBULB, 5, 20);
        fire.setFlammable(WHITE_SILKBULB, 5, 20);
        fire.setFlammable(LIGHT_GRAY_SILKBULB, 5, 20);
        fire.setFlammable(GRAY_SILKBULB, 5, 20);
        fire.setFlammable(BLACK_SILKBULB, 5, 20);
        fire.setFlammable(BROWN_SILKBULB, 5, 20);
        fire.setFlammable(RED_SILKBULB, 5, 20);
        fire.setFlammable(ORANGE_SILKBULB, 5, 20);
        fire.setFlammable(YELLOW_SILKBULB, 5, 20);
        fire.setFlammable(LIME_SILKBULB, 5, 20);
        fire.setFlammable(GREEN_SILKBULB, 5, 20);
        fire.setFlammable(CYAN_SILKBULB, 5, 20);
        fire.setFlammable(LIGHT_BLUE_SILKBULB, 5, 20);
        fire.setFlammable(BLUE_SILKBULB, 5, 20);
        fire.setFlammable(PURPLE_SILKBULB, 5, 20);
        fire.setFlammable(MAGENTA_SILKBULB, 5, 20);
        fire.setFlammable(PINK_SILKBULB, 5, 20);
        fire.setFlammable(CHARTREUSE_WOOL, 30, 60);
        fire.setFlammable(CHARTREUSE_CARPET, 60, 20);
        fire.setFlammable(CHARTREUSE_SILKBULB, 5, 20);
        fire.setFlammable(MAROON_WOOL, 30, 60);
        fire.setFlammable(MAROON_CARPET, 60, 20);
        fire.setFlammable(MAROON_SILKBULB, 5, 20);
        fire.setFlammable(INDIGO_WOOL, 30, 60);
        fire.setFlammable(INDIGO_CARPET, 60, 20);
        fire.setFlammable(INDIGO_SILKBULB, 5, 20);
        fire.setFlammable(PLUM_WOOL, 30, 60);
        fire.setFlammable(PLUM_CARPET, 60, 20);
        fire.setFlammable(PLUM_SILKBULB, 5, 20);
        fire.setFlammable(VIRIDIAN_WOOL, 30, 60);
        fire.setFlammable(VIRIDIAN_CARPET, 60, 20);
        fire.setFlammable(VIRIDIAN_SILKBULB, 5, 20);
        fire.setFlammable(TAN_WOOL, 30, 60);
        fire.setFlammable(TAN_CARPET, 60, 20);
        fire.setFlammable(TAN_SILKBULB, 5, 20);
        fire.setFlammable(SINOPIA_WOOL, 30, 60);
        fire.setFlammable(SINOPIA_CARPET, 60, 20);
        fire.setFlammable(SINOPIA_SILKBULB, 5, 20);
        fire.setFlammable(LILAC_WOOL, 30, 60);
        fire.setFlammable(LILAC_CARPET, 60, 20);
        fire.setFlammable(LILAC_SILKBULB, 5, 20);
        StrippableBlockRegistry.register(SOULBLOOM_LOG, STRIPPED_SOULBLOOM_LOG);
        StrippableBlockRegistry.register(SOULBLOOM_WOOD, STRIPPED_SOULBLOOM_WOOD);
        StrippableBlockRegistry.register(WITHERED_LOG, STRIPPED_WITHERED_LOG);
        StrippableBlockRegistry.register(WITHERED_WOOD, STRIPPED_WITHERED_WOOD);
        //FlattenableBlockRegistry.register(Blocks.DIRT_PATH, Blocks.DIRT.getDefaultState());
        FlattenableBlockRegistry.register(Blocks.FARMLAND, Blocks.DIRT_PATH.defaultBlockState());
        //TillableBlockRegistry.register(Blocks.FARMLAND, context -> true, Blocks.DIRT.getDefaultState());
        registerOxidizingSet(STEEL_BLOCK, EXPOSED_STEEL_BLOCK, WEATHERED_STEEL_BLOCK, OXIDIZED_STEEL_BLOCK, WAXED_STEEL_BLOCK, WAXED_EXPOSED_STEEL_BLOCK, WAXED_WEATHERED_STEEL_BLOCK, WAXED_OXIDIZED_STEEL_BLOCK);
        registerOxidizingSet(CUT_STEEL, EXPOSED_CUT_STEEL, WEATHERED_CUT_STEEL, OXIDIZED_CUT_STEEL, WAXED_CUT_STEEL, WAXED_EXPOSED_CUT_STEEL, WAXED_WEATHERED_CUT_STEEL, WAXED_OXIDIZED_CUT_STEEL);
        registerOxidizingSet(CUT_STEEL_STAIRS, EXPOSED_CUT_STEEL_STAIRS, WEATHERED_CUT_STEEL_STAIRS, OXIDIZED_CUT_STEEL_STAIRS, WAXED_CUT_STEEL_STAIRS, WAXED_EXPOSED_CUT_STEEL_STAIRS, WAXED_WEATHERED_CUT_STEEL_STAIRS, WAXED_OXIDIZED_CUT_STEEL_STAIRS);
        registerOxidizingSet(CUT_STEEL_SLAB, EXPOSED_CUT_STEEL_SLAB, WEATHERED_CUT_STEEL_SLAB, OXIDIZED_CUT_STEEL_SLAB, WAXED_CUT_STEEL_SLAB, WAXED_EXPOSED_CUT_STEEL_SLAB, WAXED_WEATHERED_CUT_STEEL_SLAB, WAXED_OXIDIZED_CUT_STEEL_SLAB);
        registerOxidizingSet(STEEL_GRATE, EXPOSED_STEEL_GRATE, WEATHERED_STEEL_GRATE, OXIDIZED_STEEL_GRATE, WAXED_STEEL_GRATE, WAXED_EXPOSED_STEEL_GRATE, WAXED_WEATHERED_STEEL_GRATE, WAXED_OXIDIZED_STEEL_GRATE);
        registerOxidizingSet(CHISELED_STEEL, EXPOSED_CHISELED_STEEL, WEATHERED_CHISELED_STEEL, OXIDIZED_CHISELED_STEEL, WAXED_CHISELED_STEEL, WAXED_EXPOSED_CHISELED_STEEL, WAXED_WEATHERED_CHISELED_STEEL, WAXED_OXIDIZED_CHISELED_STEEL);
        registerOxidizingSet(STEEL_FENCE, EXPOSED_STEEL_FENCE, WEATHERED_STEEL_FENCE, OXIDIZED_STEEL_FENCE, WAXED_STEEL_FENCE, WAXED_EXPOSED_STEEL_FENCE, WAXED_WEATHERED_STEEL_FENCE, WAXED_OXIDIZED_STEEL_FENCE);
        registerOxidizingSet(STEEL_DOOR, EXPOSED_STEEL_DOOR, WEATHERED_STEEL_DOOR, OXIDIZED_STEEL_DOOR, WAXED_STEEL_DOOR, WAXED_EXPOSED_STEEL_DOOR, WAXED_WEATHERED_STEEL_DOOR, WAXED_OXIDIZED_STEEL_DOOR);
        registerOxidizingSet(STEEL_TRAPDOOR, EXPOSED_STEEL_TRAPDOOR, WEATHERED_STEEL_TRAPDOOR, OXIDIZED_STEEL_TRAPDOOR, WAXED_STEEL_TRAPDOOR, WAXED_EXPOSED_STEEL_TRAPDOOR, WAXED_WEATHERED_STEEL_TRAPDOOR, WAXED_OXIDIZED_STEEL_TRAPDOOR);
    }

    private static void registerOxidizingSet(Block unaffected, Block exposed, Block weathered, Block oxidized) {
        OxidizableBlocksRegistry.registerOxidizableBlockPair(unaffected, exposed);
        OxidizableBlocksRegistry.registerOxidizableBlockPair(exposed, weathered);
        OxidizableBlocksRegistry.registerOxidizableBlockPair(weathered, oxidized);
    }

    private static void registerOxidizingSet(Block unaffected, Block exposed, Block weathered, Block oxidized, Block waxed, Block waxedExposed, Block waxedWeathered, Block waxedOxidized) {
        registerOxidizingSet(unaffected, exposed, weathered, oxidized);
        OxidizableBlocksRegistry.registerWaxableBlockPair(unaffected, waxed);
        OxidizableBlocksRegistry.registerWaxableBlockPair(exposed, waxedExposed);
        OxidizableBlocksRegistry.registerWaxableBlockPair(weathered, waxedWeathered);
        OxidizableBlocksRegistry.registerWaxableBlockPair(oxidized, waxedOxidized);
    }

}
